namespace FrenchExDev.Net.Ddd.SourceGenerator.Lib
{
    using System.Collections.Generic;
    using System.Text;

    public static class InvariantEmitter
    {
        public static string Emit(string ns, string className, IReadOnlyList<string> invariantMethodNames)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("namespace " + ns);
            sb.AppendLine("{");
            sb.AppendLine("    public partial class " + className);
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Calls all [Invariant] methods and aggregates their Results.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public FrenchExDev.Net.Result.Result EnsureInvariants()");
            sb.AppendLine("        {");

            if (invariantMethodNames.Count == 0)
            {
                sb.AppendLine("            return FrenchExDev.Net.Result.Result.Success();");
            }
            else if (invariantMethodNames.Count == 1)
            {
                sb.AppendLine("            return " + invariantMethodNames[0] + "();");
            }
            else
            {
                sb.AppendLine("            var _results = new System.Collections.Generic.List<FrenchExDev.Net.Result.Result>();");
                foreach (var name in invariantMethodNames)
                {
                    sb.AppendLine("            _results.Add(" + name + "());");
                }
                sb.AppendLine("            foreach (var _r in _results)");
                sb.AppendLine("            {");
                sb.AppendLine("                if (_r.IsFailure) return _r;");
                sb.AppendLine("            }");
                sb.AppendLine("            return FrenchExDev.Net.Result.Result.Success();");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
