using System.Linq;
using System.Text;

namespace FrenchExDev.Net.FiniteStateMachine.SourceGenerator.Lib;

public static class RichEmitter
{
    public static string EmitVisitorAndMatch(RichEmitModel m)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(m.Namespace))
        {
            sb.AppendLine($"namespace {m.Namespace};");
            sb.AppendLine();
        }

        EmitStateVisitors(sb, m);
        EmitEventVisitors(sb, m);
        EmitStateMatchExtensions(sb, m);
        EmitEventMatchExtensions(sb, m);

        return sb.ToString();
    }

    private static void EmitStateVisitors(StringBuilder sb, RichEmitModel m)
    {
        var domain = m.DomainName;

        sb.AppendLine($"public interface I{domain}StateVisitor<out TResult>");
        sb.AppendLine("{");
        foreach (var s in m.States)
            sb.AppendLine($"    TResult Visit({s.FullTypeName} state);");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine($"public interface I{domain}StateVisitor");
        sb.AppendLine("{");
        foreach (var s in m.States)
            sb.AppendLine($"    void Visit({s.FullTypeName} state);");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitEventVisitors(StringBuilder sb, RichEmitModel m)
    {
        if (m.Events.Count == 0)
            return;

        var domain = m.DomainName;

        sb.AppendLine($"public interface I{domain}EventVisitor<out TResult>");
        sb.AppendLine("{");
        foreach (var e in m.Events)
            sb.AppendLine($"    TResult Visit({e.FullTypeName} @event);");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine($"public interface I{domain}EventVisitor");
        sb.AppendLine("{");
        foreach (var e in m.Events)
            sb.AppendLine($"    void Visit({e.FullTypeName} @event);");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitStateMatchExtensions(StringBuilder sb, RichEmitModel m)
    {
        sb.AppendLine($"[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine($"public static class {m.DomainName}StateExtensions");
        sb.AppendLine("{");
        EmitMatchMethod(sb, m.StateInterfaceName, m.States.Select(s => (s.TypeName, s.FullTypeName)).ToList(), "state");
        EmitMatchVoidMethod(sb, m.StateInterfaceName, m.States.Select(s => (s.TypeName, s.FullTypeName)).ToList(), "state");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitEventMatchExtensions(StringBuilder sb, RichEmitModel m)
    {
        if (m.Events.Count == 0)
            return;

        sb.AppendLine($"[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine($"public static class {m.DomainName}EventExtensions");
        sb.AppendLine("{");
        EmitMatchMethod(sb, m.EventInterfaceName, m.Events.Select(e => (e.TypeName, e.FullTypeName)).ToList(), "@event");
        EmitMatchVoidMethod(sb, m.EventInterfaceName, m.Events.Select(e => (e.TypeName, e.FullTypeName)).ToList(), "@event");
        sb.AppendLine("}");
    }

    public static string EmitAcceptForState(RichEmitModel m, RichStateEmitModel state)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(m.Namespace))
        {
            sb.AppendLine($"namespace {m.Namespace};");
            sb.AppendLine();
        }

        var domain = m.DomainName;

        sb.AppendLine($"public partial record {state.TypeName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public TResult Accept<TResult>(I{domain}StateVisitor<TResult> visitor) => visitor.Visit(this);");
        sb.AppendLine($"    public void Accept(I{domain}StateVisitor visitor) => visitor.Visit(this);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitAcceptForEvent(RichEmitModel m, RichEventEmitModel evt)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(m.Namespace))
        {
            sb.AppendLine($"namespace {m.Namespace};");
            sb.AppendLine();
        }

        var domain = m.DomainName;

        sb.AppendLine($"public partial record {evt.TypeName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public TResult Accept<TResult>(I{domain}EventVisitor<TResult> visitor) => visitor.Visit(this);");
        sb.AppendLine($"    public void Accept(I{domain}EventVisitor visitor) => visitor.Visit(this);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitMatchMethod(
        StringBuilder sb, string interfaceName,
        System.Collections.Generic.List<(string TypeName, string FullTypeName)> types,
        string paramName)
    {
        var paramNames = types.Select(t => ToCamelCase(t.TypeName)).ToList();
        var funcParams = string.Join(",\n        ",
            types.Select((t, i) => $"global::System.Func<{t.FullTypeName}, TResult> {paramNames[i]}"));

        sb.AppendLine($"    public static TResult Match<TResult>(");
        sb.AppendLine($"        this {interfaceName} {paramName},");
        sb.AppendLine($"        {funcParams})");
        sb.AppendLine("    {");
        sb.AppendLine($"        return {paramName} switch");
        sb.AppendLine("        {");
        for (int i = 0; i < types.Count; i++)
            sb.AppendLine($"            {types[i].FullTypeName} s => {paramNames[i]}(s),");
        sb.AppendLine($"            _ => throw new global::System.InvalidOperationException($\"Unknown type: {{{paramName}.GetType().Name}}\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitMatchVoidMethod(
        StringBuilder sb, string interfaceName,
        System.Collections.Generic.List<(string TypeName, string FullTypeName)> types,
        string paramName)
    {
        var paramNames = types.Select(t => ToCamelCase(t.TypeName)).ToList();
        var actionParams = string.Join(",\n        ",
            types.Select((t, i) => $"global::System.Action<{t.FullTypeName}> {paramNames[i]}"));

        sb.AppendLine($"    public static void Match(");
        sb.AppendLine($"        this {interfaceName} {paramName},");
        sb.AppendLine($"        {actionParams})");
        sb.AppendLine("    {");
        sb.AppendLine($"        switch ({paramName})");
        sb.AppendLine("        {");
        for (int i = 0; i < types.Count; i++)
        {
            sb.AppendLine($"            case {types[i].FullTypeName} s: {paramNames[i]}(s); break;");
        }
        sb.AppendLine($"            default: throw new global::System.InvalidOperationException($\"Unknown type: {{{paramName}.GetType().Name}}\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}
