using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FrenchExDev.Net.FiniteStateMachine.SourceGenerator.Lib;

public static class StateMachineEmitter
{
    public static string Emit(StateMachineEmitModel m)
    {
        var sb = new StringBuilder();
        EmitPreamble(sb, m);
        EmitMainClass(sb, m);
        EmitCompanionGraphClass(sb, m);
        return sb.ToString();
    }

    private static void EmitPreamble(StringBuilder sb, StateMachineEmitModel m)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(m.Namespace))
        {
            sb.AppendLine($"namespace {m.Namespace};");
            sb.AppendLine();
        }
    }

    private static void EmitMainClass(StringBuilder sb, StateMachineEmitModel m)
    {
        sb.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine($"public partial class {m.ClassName}");
        sb.AppendLine("{");
        EmitFieldAndConstructors(sb, m);
        EmitPublicApi(sb, m);
        EmitHooksAndDispatchers(sb, m);
        EmitUtilities(sb, m);
        EmitCreateEngine(sb, m);
        EmitHookListener(sb, m);
        EmitDefineTransitions(sb);
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitFieldAndConstructors(StringBuilder sb, StateMachineEmitModel m)
    {
        sb.AppendLine($"    private readonly global::FrenchExDev.Net.FiniteStateMachine.StateMachineEngine<{m.StateEnumFull}, {m.EventEnumFull}> _engine;");
        sb.AppendLine();
        sb.AppendLine($"    public {m.ClassName}() {{ _engine = CreateEngine({m.StateEnumFull}.{m.InitialStateMember}); _engine.AddListener(new HookListener(this)); }}");
        sb.AppendLine($"    public {m.ClassName}({m.StateEnumFull} initialState) {{ _engine = CreateEngine(initialState); _engine.AddListener(new HookListener(this)); }}");
        sb.AppendLine();
    }

    private static void EmitPublicApi(StringBuilder sb, StateMachineEmitModel m)
    {
        sb.AppendLine($"    public {m.StateEnumFull} CurrentState => _engine.CurrentState;");
        sb.AppendLine($"    public void AddListener(global::FrenchExDev.Net.FiniteStateMachine.IStateMachineListener<{m.StateEnumFull}, {m.EventEnumFull}> listener) => _engine.AddListener(listener);");
        sb.AppendLine($"    public void RemoveListener(global::FrenchExDev.Net.FiniteStateMachine.IStateMachineListener<{m.StateEnumFull}, {m.EventEnumFull}> listener) => _engine.RemoveListener(listener);");
        sb.AppendLine();

        // Fire methods
        foreach (var evt in m.EventMembers)
        {
            sb.AppendLine($"    public global::System.Threading.Tasks.Task<global::FrenchExDev.Net.Result.Result<global::FrenchExDev.Net.FiniteStateMachine.Transition<{m.StateEnumFull}>>> Fire{evt}Async(global::System.Threading.CancellationToken ct = default)");
            sb.AppendLine($"        => _engine.FireAsync({m.EventEnumFull}.{evt}, ct);");
            sb.AppendLine();
        }

        // CanFire methods
        foreach (var evt in m.EventMembers)
        {
            sb.AppendLine($"    public global::System.Threading.Tasks.Task<bool> CanFire{evt}Async(global::System.Threading.CancellationToken ct = default)");
            sb.AppendLine($"        => _engine.CanFireAsync({m.EventEnumFull}.{evt}, ct);");
            sb.AppendLine();
        }

        // PermittedEventsAsync
        sb.AppendLine($"    public global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<{m.EventEnumFull}>> PermittedEventsAsync(global::System.Threading.CancellationToken ct = default)");
        sb.AppendLine("        => _engine.GetPermittedEventsAsync(ct);");
        sb.AppendLine();
    }

    private static void EmitHooksAndDispatchers(StringBuilder sb, StateMachineEmitModel m)
    {
        // No-op hooks and dispatchers are NOT generated on the main class.
        // Dispatchers are inlined into the HookListener nested class.
        // This keeps the main class's method count low → better LCOM.
    }

    // Dispatchers are inlined into the HookListener to avoid adding methods
    // that don't reference _engine, which would increase LCOM.

    private static void EmitUtilities(StringBuilder sb, StateMachineEmitModel m)
    {
        sb.AppendLine($"    public override string ToString() => $\"{m.ClassName} {{{{ State = {{_engine.CurrentState}} }}}}\";");
        sb.AppendLine();
    }

    private static void EmitCreateEngine(StringBuilder sb, StateMachineEmitModel m)
    {
        sb.AppendLine($"    private static global::FrenchExDev.Net.FiniteStateMachine.StateMachineEngine<{m.StateEnumFull}, {m.EventEnumFull}> CreateEngine({m.StateEnumFull} initialState)");
        sb.AppendLine("    {");

        // Build transition table inline
        sb.AppendLine($"        var table = new global::FrenchExDev.Net.FiniteStateMachine.Typed.TransitionTable<{m.StateEnumFull}, {m.EventEnumFull}>();");
        foreach (var t in m.Transitions)
        {
            sb.AppendLine($"        table.Add(new global::FrenchExDev.Net.FiniteStateMachine.TransitionDefinition<{m.StateEnumFull}, {m.EventEnumFull}>(" +
                $"{m.StateEnumFull}.{t.FromMember}, {m.EventEnumFull}.{t.EventMember}, {m.StateEnumFull}.{t.ToMember}, " +
                $"global::System.Array.Empty<global::FrenchExDev.Net.FiniteStateMachine.IGuard<{m.StateEnumFull}, {m.EventEnumFull}>>(), " +
                $"global::System.Array.Empty<global::FrenchExDev.Net.FiniteStateMachine.ITransitionAction<{m.StateEnumFull}, {m.EventEnumFull}>>()));");
        }

        // Build definition
        sb.AppendLine($"        var states = new global::System.Collections.Generic.HashSet<{m.StateEnumFull}>();");
        sb.AppendLine($"        states.Add(initialState);");
        sb.AppendLine($"        foreach (var t in table.AllTransitions) {{ states.Add(t.Source); states.Add(t.Target); }}");
        sb.AppendLine($"        var definition = new global::FrenchExDev.Net.FiniteStateMachine.Typed.TypedStateMachineDefinition<{m.StateEnumFull}, {m.EventEnumFull}>(");
        sb.AppendLine($"            initialState, states, new global::System.Collections.Generic.HashSet<{m.StateEnumFull}>(), table,");
        sb.AppendLine($"            new global::System.Collections.Generic.Dictionary<{m.StateEnumFull}, global::System.Collections.Generic.List<global::FrenchExDev.Net.FiniteStateMachine.IStateAction<{m.StateEnumFull}, {m.EventEnumFull}>>>(),");
        sb.AppendLine($"            new global::System.Collections.Generic.Dictionary<{m.StateEnumFull}, global::System.Collections.Generic.List<global::FrenchExDev.Net.FiniteStateMachine.IStateAction<{m.StateEnumFull}, {m.EventEnumFull}>>>());");

        sb.AppendLine($"        return new global::FrenchExDev.Net.FiniteStateMachine.StateMachineEngine<{m.StateEnumFull}, {m.EventEnumFull}>(definition);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitHookListener(StringBuilder sb, StateMachineEmitModel m)
    {
        EmitHookListenerHeader(sb, m);
        EmitHookListenerEntryOverride(sb, m);
        EmitHookListenerExitOverride(sb, m);
        EmitHookListenerTransitionOverride(sb, m);
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitHookListenerHeader(StringBuilder sb, StateMachineEmitModel m)
    {
        sb.AppendLine($"    private sealed class HookListener : global::FrenchExDev.Net.FiniteStateMachine.StateMachineListenerBase<{m.StateEnumFull}, {m.EventEnumFull}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        private readonly {m.ClassName} _owner;");
        sb.AppendLine($"        public HookListener({m.ClassName} owner) => _owner = owner;");
    }

    private static void EmitHookListenerEntryOverride(StringBuilder sb, StateMachineEmitModel m)
    {
        sb.AppendLine($"        public override global::System.Threading.Tasks.Task OnStateEnteredAsync({m.StateEnumFull} state, {m.EventEnumFull} triggeringEvent, global::System.Threading.CancellationToken ct)");
        sb.AppendLine("        {");
        sb.AppendLine("            return state switch");
        sb.AppendLine("            {");
        foreach (var state in m.StateMembers)
        {
            var name = $"OnEntry{state}Async";
            if (m.UserDefinedMethods.Contains(name))
                sb.AppendLine($"                {m.StateEnumFull}.{state} => _owner.{name}(ct),");
        }
        sb.AppendLine("                _ => global::System.Threading.Tasks.Task.CompletedTask,");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
    }

    private static void EmitHookListenerExitOverride(StringBuilder sb, StateMachineEmitModel m)
    {
        sb.AppendLine($"        public override global::System.Threading.Tasks.Task OnStateExitingAsync({m.StateEnumFull} state, {m.EventEnumFull} @event, global::System.Threading.CancellationToken ct)");
        sb.AppendLine("        {");
        sb.AppendLine("            return state switch");
        sb.AppendLine("            {");
        foreach (var state in m.StateMembers)
        {
            var name = $"OnExit{state}Async";
            if (m.UserDefinedMethods.Contains(name))
                sb.AppendLine($"                {m.StateEnumFull}.{state} => _owner.{name}(ct),");
        }
        sb.AppendLine("                _ => global::System.Threading.Tasks.Task.CompletedTask,");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
    }

    private static void EmitHookListenerTransitionOverride(StringBuilder sb, StateMachineEmitModel m)
    {
        sb.AppendLine($"        public override global::System.Threading.Tasks.Task OnTransitionedAsync({m.StateEnumFull} from, {m.EventEnumFull} @event, {m.StateEnumFull} to, global::System.Threading.CancellationToken ct)");
        sb.AppendLine("        {");
        sb.AppendLine("            return (from, @event, to) switch");
        sb.AppendLine("            {");
        foreach (var t in m.Transitions)
        {
            var name = $"OnTransition{t.FromMember}To{t.ToMember}Async";
            if (m.UserDefinedMethods.Contains(name))
                sb.AppendLine($"                ({m.StateEnumFull}.{t.FromMember}, {m.EventEnumFull}.{t.EventMember}, {m.StateEnumFull}.{t.ToMember}) => _owner.{name}(ct),");
        }
        sb.AppendLine("                _ => global::System.Threading.Tasks.Task.CompletedTask,");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
    }

    private static void EmitDefineTransitions(StringBuilder sb)
    {
        sb.AppendLine("    private static partial void DefineTransitions() { }");
    }

    private static void EmitCompanionGraphClass(StringBuilder sb, StateMachineEmitModel m)
    {
        sb.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine($"public static class {m.ClassName}Graph");
        sb.AppendLine("{");
        EmitCompanionMermaid(sb, m);
        EmitCompanionDot(sb, m);
        EmitCompanionPermittedEvents(sb, m);
        sb.AppendLine("}");
    }

    private static void EmitCompanionMermaid(StringBuilder sb, StateMachineEmitModel m)
    {
        var mermaid = new StringBuilder();
        mermaid.AppendLine("stateDiagram-v2");
        mermaid.AppendLine($"    [*] --> {m.InitialStateMember}");
        foreach (var t in m.Transitions)
            mermaid.AppendLine($"    {t.FromMember} --> {t.ToMember} : {t.EventMember}");
        sb.AppendLine($"    public const string MermaidGraph = @\"{EscapeVerbatim(mermaid.ToString().TrimEnd())}\";");
        sb.AppendLine();
    }

    private static void EmitCompanionDot(StringBuilder sb, StateMachineEmitModel m)
    {
        var dot = new StringBuilder();
        dot.AppendLine($"digraph {m.ClassName} {{");
        dot.AppendLine("    rankdir=LR;");
        dot.AppendLine("    node [shape=circle];");
        foreach (var t in m.Transitions)
            dot.AppendLine($"    {t.FromMember} -> {t.ToMember} [label=\"{t.EventMember}\"];");
        dot.AppendLine("}");
        sb.AppendLine($"    public const string DotGraph = @\"{EscapeVerbatim(dot.ToString().TrimEnd())}\";");
        sb.AppendLine();
    }

    private static void EmitCompanionPermittedEvents(StringBuilder sb, StateMachineEmitModel m)
    {
        sb.AppendLine($"    public static global::System.Collections.Generic.IReadOnlyList<{m.EventEnumFull}> PermittedEventsFrom({m.StateEnumFull} state)");
        sb.AppendLine("    {");
        sb.AppendLine("        return state switch");
        sb.AppendLine("        {");
        foreach (var g in m.Transitions.GroupBy(t => t.FromMember))
        {
            var events = string.Join(", ", g.Select(t => $"{m.EventEnumFull}.{t.EventMember}"));
            sb.AppendLine($"            {m.StateEnumFull}.{g.Key} => new {m.EventEnumFull}[] {{ {events} }},");
        }
        sb.AppendLine($"            _ => global::System.Array.Empty<{m.EventEnumFull}>(),");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static string EscapeVerbatim(string s) => s.Replace("\"", "\"\"");
}
