namespace FrenchExDev.Net.Dsl.SourceGenerator.Lib;

using System.Text;

/// <summary>
/// Emits the MetamodelRegistry.g.cs source from discovered concept models.
/// No Roslyn dependency — works with plain string data.
/// </summary>
public static class MetamodelRegistryEmitter
{
    public static string Emit(IReadOnlyList<ConceptEmitModel> concepts)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace FrenchExDev.Net.Dsl.Generated;");
        sb.AppendLine();
        sb.AppendLine("using FrenchExDev.Net.Dsl;");
        sb.AppendLine();
        sb.AppendLine("public static class MetamodelRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    public static global::System.Collections.Generic.IReadOnlyDictionary<string, ConceptDescriptor> Concepts { get; } =");
        sb.AppendLine("        new global::System.Collections.Generic.Dictionary<string, ConceptDescriptor>");
        sb.AppendLine("        {");

        foreach (var concept in concepts)
        {
            sb.AppendLine($"            [\"{concept.Name}\"] = new ConceptDescriptor");
            sb.AppendLine("            {");
            sb.AppendLine($"                Name = \"{concept.Name}\",");
            sb.AppendLine($"                AttributeType = typeof({concept.AttributeTypeFullName}),");
            sb.AppendLine($"                ConceptType = typeof({concept.ConceptTypeFullName}),");

            // Inherits
            if (concept.Inherits.Count > 0)
            {
                var inherits = string.Join(", ", concept.Inherits.Select(i => $"\"{i}\""));
                sb.AppendLine($"                Inherits = new string[] {{ {inherits} }},");
            }

            // Properties
            if (concept.Properties.Count > 0)
            {
                sb.AppendLine("                Properties = new PropertyDescriptor[]");
                sb.AppendLine("                {");
                foreach (var prop in concept.Properties)
                {
                    sb.AppendLine($"                    new PropertyDescriptor {{ Name = \"{prop.Name}\", Type = \"{prop.Type}\", Required = {(prop.Required ? "true" : "false")} }},");
                }
                sb.AppendLine("                },");
            }

            // Constraints
            if (concept.Constraints.Count > 0)
            {
                sb.AppendLine("                Constraints = new ConstraintDescriptor[]");
                sb.AppendLine("                {");
                foreach (var c in concept.Constraints)
                {
                    var msg = c.Message is not null ? $"\"{c.Message}\"" : "null";
                    sb.AppendLine($"                    new ConstraintDescriptor {{ Name = \"{c.Name}\", MethodName = \"{c.MethodName}\", Message = {msg} }},");
                }
                sb.AppendLine("                },");
            }

            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

public sealed class ConceptEmitModel
{
    public string Name { get; set; } = "";
    public string AttributeTypeFullName { get; set; } = "";
    public string ConceptTypeFullName { get; set; } = "";
    public IReadOnlyList<string> Inherits { get; set; } = Array.Empty<string>();
    public IReadOnlyList<PropertyEmitModel> Properties { get; set; } = Array.Empty<PropertyEmitModel>();
    public IReadOnlyList<ConstraintEmitModel> Constraints { get; set; } = Array.Empty<ConstraintEmitModel>();
}

public sealed class PropertyEmitModel
{
    public string Name { get; set; } = "";
    public string Type { get; set; } = "";
    public bool Required { get; set; }
}

public sealed class ConstraintEmitModel
{
    public string Name { get; set; } = "";
    public string MethodName { get; set; } = "";
    public string? Message { get; set; }
}
