namespace FrenchExDev.Net.Requirements.SourceGenerator.Lib;

using System.Text;

public static class RequirementRegistryEmitter
{
    public static string Emit(IReadOnlyList<RequirementEmitModel> requirements)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace FrenchExDev.Net.Requirements.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    using System;");
        sb.AppendLine("    using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("    public static class RequirementRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        public static IReadOnlyDictionary<Type, RequirementInfo> All { get; } =");
        sb.AppendLine("            new Dictionary<Type, RequirementInfo>");
        sb.AppendLine("            {");

        foreach (var req in requirements)
        {
            sb.AppendLine($"                [typeof({req.TypeFullName})] = new RequirementInfo(");
            sb.AppendLine($"                    typeof({req.TypeFullName}),");
            sb.AppendLine($"                    RequirementKind.{req.Kind},");
            sb.AppendLine($"                    \"{EscapeString(req.Title)}\",");
            sb.AppendLine($"                    {(req.ParentTypeFullName != null ? $"typeof({req.ParentTypeFullName})" : "null")},");

            if (req.AcceptanceCriteria.Count > 0)
            {
                var acs = new List<string>();
                foreach (var ac in req.AcceptanceCriteria)
                {
                    acs.Add($"\"{ac}\"");
                }
                sb.AppendLine($"                    new string[] {{ {string.Join(", ", acs)} }}),");
            }
            else
            {
                sb.AppendLine("                    Array.Empty<string>()),");
            }
        }

        sb.AppendLine("            };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public sealed class RequirementInfo");
        sb.AppendLine("    {");
        sb.AppendLine("        public Type Type { get; }");
        sb.AppendLine("        public RequirementKind Kind { get; }");
        sb.AppendLine("        public string Title { get; }");
        sb.AppendLine("        public Type? Parent { get; }");
        sb.AppendLine("        public string[] AcceptanceCriteria { get; }");
        sb.AppendLine();
        sb.AppendLine("        public RequirementInfo(Type type, RequirementKind kind, string title, Type? parent, string[] acceptanceCriteria)");
        sb.AppendLine("        {");
        sb.AppendLine("            Type = type; Kind = kind; Title = title; Parent = parent; AcceptanceCriteria = acceptanceCriteria;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public enum RequirementKind { Epic, Feature, Story, Task, Bug }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EscapeString(string s) => s.Replace("\"", "\\\"");
}

public sealed class RequirementEmitModel
{
    public string TypeFullName { get; set; } = "";
    public string Kind { get; set; } = "";
    public string Title { get; set; } = "";
    public string? ParentTypeFullName { get; set; }
    public List<string> AcceptanceCriteria { get; set; } = new List<string>();
}
