using FrenchExDev.Net.Ddd.Entity.Dsl.SourceGenerator.Lib;
using Xunit;

namespace FrenchExDev.Net.Ddd.Entity.Dsl.Tests;

public class DddEntityDslBridgeEmitterTests
{
    [Fact]
    public void Emit_adds_mapped_entity_attribute()
    {
        var model = new DddBridgeModel
        {
            Namespace = "MyApp.Domain",
            ClassName = "Order",
            IsAggregateRoot = true
        };

        var code = DddEntityDslBridgeEmitter.Emit(model);

        Assert.Contains("[global::FrenchExDev.Net.Entity.Dsl.Attributes.MappedEntity]", code);
        Assert.Contains("public partial class Order", code);
    }

    [Fact]
    public void Emit_contains_auto_generated_header()
    {
        var model = new DddBridgeModel
        {
            Namespace = "MyApp.Domain",
            ClassName = "Product",
            IsEntity = true
        };

        var code = DddEntityDslBridgeEmitter.Emit(model);

        Assert.StartsWith("// <auto-generated/>", code);
        Assert.Contains("Ddd.Entity.Dsl bridge", code);
    }

    [Fact]
    public void Emit_uses_correct_namespace()
    {
        var model = new DddBridgeModel
        {
            Namespace = "MyApp.Domain.Entities",
            ClassName = "Customer"
        };

        var code = DddEntityDslBridgeEmitter.Emit(model);

        Assert.Contains("namespace MyApp.Domain.Entities;", code);
    }
}
