namespace FrenchExDev.Net.Entity.Dsl.SourceGenerator.Lib;

using System.Text;

/// <summary>
/// Emits the AddDbContext extension method — the only DI registration not handled by [Injectable].
/// </summary>
public static class DbContextRegistrationEmitter
{
    public static string Emit(DbContextEmitModel model)
    {
        var sb = new StringBuilder(512);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine($"public static class {model.ClassName}Registration");
        sb.AppendLine("{");
        sb.AppendLine($"    public static IServiceCollection Add{model.ClassName}(");
        sb.AppendLine("        this IServiceCollection services,");
        sb.AppendLine("        global::System.Action<Microsoft.EntityFrameworkCore.DbContextOptionsBuilder> configureDbContext)");
        sb.AppendLine("    {");
        sb.AppendLine($"        services.AddDbContext<{model.Namespace}.{model.ClassName}>(configureDbContext);");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
