namespace FrenchExDev.Net.Entity.Dsl.SourceGenerator.Lib;

using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Emits the Generation Gap files for entity configuration:
/// 1. {Entity}ConfigurationBase.g.cs — abstract base with virtual Configure* methods (always regenerated)
/// 2. {Entity}Configuration.g.cs — partial stub (always regenerated, developer extends via second partial)
/// 3. {Entity}ConfigurationRegistration.g.cs — IEntityTypeConfiguration&lt;T&gt; delegate (always regenerated)
/// </summary>
public static class EntityConfigurationEmitter
{
    /// <summary>Emits the abstract base class with all virtual Configure* methods.</summary>
    public static string EmitBase(EntityEmitModel model)
    {
        var sb = new StringBuilder(4096);
        EmitFileHeader(sb);
        sb.AppendLine($"namespace {model.Namespace}.Configuration;");
        sb.AppendLine();
        sb.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine($"public abstract class {model.ClassName}ConfigurationBase");
        sb.AppendLine("{");

        // PreConfigure hook
        sb.AppendLine("    protected virtual void PreConfigure(");
        sb.AppendLine($"        Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<{model.ClassFullName}> builder) {{ }}");
        sb.AppendLine();

        // PostConfigure hook
        sb.AppendLine("    protected virtual void PostConfigure(");
        sb.AppendLine($"        Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<{model.ClassFullName}> builder) {{ }}");
        sb.AppendLine();

        // ConfigureTable
        EmitConfigureTable(sb, model);

        // ConfigurePrimaryKey
        EmitConfigurePrimaryKey(sb, model);

        // Per-property Configure methods
        foreach (var prop in model.Properties)
        {
            if (prop.IsNotMapped) continue;
            EmitConfigureProperty(sb, model, prop);
        }

        // Navigation property relationships
        EmitConfigureRelationships(sb, model);

        // Orchestrator
        EmitOrchestrator(sb, model);

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>Emits the partial class stub extending Base.</summary>
    public static string EmitPartialStub(EntityEmitModel model)
    {
        var sb = new StringBuilder(512);
        EmitFileHeader(sb);
        sb.AppendLine($"namespace {model.Namespace}.Configuration;");
        sb.AppendLine();
        sb.AppendLine($"public partial class {model.ClassName}Configuration : {model.ClassName}ConfigurationBase");
        sb.AppendLine("{");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>Emits the IEntityTypeConfiguration&lt;T&gt; registration that delegates to the partial class.</summary>
    public static string EmitRegistration(EntityEmitModel model)
    {
        var sb = new StringBuilder(512);
        EmitFileHeader(sb);
        sb.AppendLine($"namespace {model.Namespace}.Configuration;");
        sb.AppendLine();
        sb.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine($"public sealed class {model.ClassName}ConfigurationRegistration");
        sb.AppendLine($"    : Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<{model.ClassFullName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public void Configure(");
        sb.AppendLine($"        Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<{model.ClassFullName}> builder)");
        sb.AppendLine("    {");
        sb.AppendLine($"        new {model.ClassName}Configuration().Configure(builder);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }

    private static void EmitConfigureTable(StringBuilder sb, EntityEmitModel model)
    {
        sb.AppendLine("    protected virtual void ConfigureTable(");
        sb.AppendLine($"        Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<{model.ClassFullName}> builder)");
        sb.AppendLine("    {");
        if (model.TableName != null && model.Schema != null)
            sb.AppendLine($"        builder.ToTable(\"{model.TableName}\", \"{model.Schema}\");");
        else if (model.TableName != null)
            sb.AppendLine($"        builder.ToTable(\"{model.TableName}\");");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitConfigurePrimaryKey(StringBuilder sb, EntityEmitModel model)
    {
        if (model.PrimaryKeyProperties.Count == 0) return;

        sb.AppendLine("    protected virtual void ConfigurePrimaryKey(");
        sb.AppendLine($"        Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<{model.ClassFullName}> builder)");
        sb.AppendLine("    {");

        var sorted = model.PrimaryKeyProperties.OrderBy(k => k.Order).ToList();

        if (sorted.Count == 1)
        {
            sb.AppendLine($"        builder.HasKey(e => e.{sorted[0].PropertyName});");
            EmitValueGenerated(sb, sorted[0]);
        }
        else
        {
            var keyExpr = string.Join(", ", sorted.Select(k => $"e.{k.PropertyName}"));
            sb.AppendLine($"        builder.HasKey(e => new {{ {keyExpr} }});");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitValueGenerated(StringBuilder sb, KeyPropertyModel key)
    {
        switch (key.ValueGenerated)
        {
            case "OnAdd":
                sb.AppendLine($"        builder.Property(e => e.{key.PropertyName}).ValueGeneratedOnAdd();");
                break;
            case "OnUpdate":
                sb.AppendLine($"        builder.Property(e => e.{key.PropertyName}).ValueGeneratedOnUpdate();");
                break;
            case "OnAddOrUpdate":
                sb.AppendLine($"        builder.Property(e => e.{key.PropertyName}).ValueGeneratedOnAddOrUpdate();");
                break;
            case "None":
                sb.AppendLine($"        builder.Property(e => e.{key.PropertyName}).ValueGeneratedNever();");
                break;
        }
    }

    private static void EmitConfigureProperty(StringBuilder sb, EntityEmitModel model, PropertyConfigModel prop)
    {
        sb.AppendLine($"    protected virtual void Configure{prop.PropertyName}(");
        sb.AppendLine($"        Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<{model.ClassFullName}> builder)");
        sb.AppendLine("    {");

        var chain = new List<string>();

        if (prop.ColumnName != null)
            chain.Add($".HasColumnName(\"{prop.ColumnName}\")");
        if (prop.ColumnType != null)
            chain.Add($".HasColumnType(\"{prop.ColumnType}\")");
        if (prop.ColumnOrder >= 0)
            chain.Add($".HasColumnOrder({prop.ColumnOrder})");
        if (prop.IsRequired)
            chain.Add(".IsRequired()");
        if (prop.MaxLength > 0)
            chain.Add($".HasMaxLength({prop.MaxLength})");

        if (chain.Count > 0)
        {
            sb.Append($"        builder.Property(e => e.{prop.PropertyName})");
            foreach (var c in chain)
            {
                sb.AppendLine();
                sb.Append($"            {c}");
            }
            sb.AppendLine(";");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitConfigureRelationships(StringBuilder sb, EntityEmitModel model)
    {
        if (model.NavigationProperties.Count == 0) return;

        sb.AppendLine("    protected virtual void ConfigureRelationships(");
        sb.AppendLine($"        Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<{model.ClassFullName}> builder)");
        sb.AppendLine("    {");

        foreach (var nav in model.NavigationProperties)
        {
            sb.AppendLine($"        builder.Navigation(\"{nav.PropertyName}\").AutoInclude(false);");
            sb.AppendLine($"        builder.HasMany(\"{nav.PropertyName}\").WithOne()");
            sb.AppendLine($"            .OnDelete(Microsoft.EntityFrameworkCore.DeleteBehavior.{nav.OnDelete});");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitOrchestrator(StringBuilder sb, EntityEmitModel model)
    {
        sb.AppendLine("    public void Configure(");
        sb.AppendLine($"        Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<{model.ClassFullName}> builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        PreConfigure(builder);");
        sb.AppendLine("        ConfigureTable(builder);");

        if (model.PrimaryKeyProperties.Count > 0)
            sb.AppendLine("        ConfigurePrimaryKey(builder);");

        foreach (var prop in model.Properties)
        {
            if (prop.IsNotMapped) continue;
            sb.AppendLine($"        Configure{prop.PropertyName}(builder);");
        }

        if (model.NavigationProperties.Count > 0)
            sb.AppendLine("        ConfigureRelationships(builder);");

        sb.AppendLine("        PostConfigure(builder);");
        sb.AppendLine("    }");
    }
}
