namespace FrenchExDev.Net.Entity.Dsl.SourceGenerator.Lib;

using System.Text;

/// <summary>
/// Emits the Generation Gap files for repositories:
/// 1. I{Entity}Repository.g.cs — entity-specific interface (always regenerated)
/// 2. {Entity}Repository.g.cs — partial stub with [Injectable] (always regenerated)
///
/// The per-entity abstract base (OrderRepositoryBase) is NO LONGER generated.
/// Instead, RepositoryBase&lt;T&gt; lives in Abstractions as a hand-written generic.
/// The developer creates a project-level intermediate (MyProjectRepository&lt;T&gt;)
/// and declares it via [DbContext(RepositoryBase = typeof(MyProjectRepository&lt;&gt;))].
///
/// Hierarchy:
///   RepositoryBase&lt;T&gt;          (Abstractions — hand-written)
///       ↑
///   MyProjectRepository&lt;T&gt;     (developer-written, project-wide)
///       ↑
///   OrderRepository             (SG-generated partial + developer partial)
/// </summary>
public static class RepositoryEmitter
{
    public static string EmitInterface(RepositoryEmitModel model)
    {
        var sb = new StringBuilder(512);
        EmitFileHeader(sb);
        sb.AppendLine($"namespace {model.Namespace}.Repositories;");
        sb.AppendLine();
        sb.AppendLine($"public interface I{model.EntityClassName}Repository : global::FrenchExDev.Net.Entity.Dsl.Abstractions.IRepository<{model.EntityClassFull}>");
        sb.AppendLine("{");
        if (!model.IsCompositeKey)
        {
            sb.AppendLine($"    global::System.Threading.Tasks.ValueTask<{model.EntityClassFull}?> FindByIdAsync({model.PrimaryKeyTypeFull} id);");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string EmitPartialStub(RepositoryEmitModel model)
    {
        var baseType = model.RepositoryBaseTypeFull
            ?? $"global::FrenchExDev.Net.Entity.Dsl.Abstractions.RepositoryBase<{model.EntityClassFull}>";

        var sb = new StringBuilder(1024);
        EmitFileHeader(sb);
        sb.AppendLine($"namespace {model.Namespace}.Repositories;");
        sb.AppendLine();
        sb.AppendLine("[global::FrenchExDev.Net.Injectable.Attributes.Injectable(");
        sb.AppendLine($"    Scope = global::FrenchExDev.Net.Injectable.Attributes.Scope.Scoped,");
        sb.AppendLine($"    As = new global::System.Type[] {{ typeof(I{model.EntityClassName}Repository) }})]");
        sb.AppendLine($"public partial class {model.EntityClassName}Repository : {baseType}, I{model.EntityClassName}Repository");
        sb.AppendLine("{");
        sb.AppendLine($"    public {model.EntityClassName}Repository({model.DbContextTypeFull} context) : base(context) {{ }}");

        // Typed FindByIdAsync (bridges the interface method to the generic base)
        if (!model.IsCompositeKey)
        {
            sb.AppendLine();
            sb.AppendLine($"    public virtual global::System.Threading.Tasks.ValueTask<{model.EntityClassFull}?> FindByIdAsync({model.PrimaryKeyTypeFull} id)");
            sb.AppendLine("        => FindByIdAsync(new object[] { id });");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }
}
