<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\FrenchExDev.Net.Diem\FrenchExDev.Net.Diem.csproj" />
    <ProjectReference Include="..\..\src\FrenchExDev.Net.Diem.Media\FrenchExDev.Net.Diem.Media.csproj" />
    <ProjectReference Include="..\..\src\FrenchExDev.Net.Diem.Media.FileSystem\FrenchExDev.Net.Diem.Media.FileSystem.csproj" />
    <ProjectReference Include="..\..\src\FrenchExDev.Net.Diem.Search\FrenchExDev.Net.Diem.Search.csproj" />
    <ProjectReference Include="..\..\src\FrenchExDev.Net.Diem.Identity\FrenchExDev.Net.Diem.Identity.csproj" />
    <ProjectReference Include="..\..\src\FrenchExDev.Net.Diem.Caching\FrenchExDev.Net.Diem.Caching.csproj" />
    <ProjectReference Include="..\..\src\FrenchExDev.Net.Diem.Notifications\FrenchExDev.Net.Diem.Notifications.csproj" />
  </ItemGroup>
</Project>
