using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FrenchExDev.Net.Packer.Bundle.SourceGenerator.Lib;

/// <summary>
/// Emits C# source code for a Packer plugin type record + WriteTo method.
/// Called by the SG for each scraped plugin JSON file.
/// </summary>
public static class PluginTypeEmitter
{
    /// <summary>
    /// Emits a partial class record for a plugin type (builder/provisioner/post-processor/datasource).
    /// </summary>
    public static string EmitRecord(string ns, ScrapePluginModel model)
    {
        var className = NamingHelper.ToClassName(model.TypeName, model.PluginKind);
        var baseClass = model.PluginKind switch
        {
            "builder" => "PackerSource",
            "provisioner" => "PackerProvisioner",
            "post-processor" => "PackerPostProcessor",
            _ => "PackerProvisioner" // datasources use provisioner-like pattern
        };

        // Filter out packer_* internal fields and deduplicate by PascalCase name
        var seen = new HashSet<string>();
        var fields = model.Fields
            .Where(f => !f.HclName.StartsWith("packer_"))
            .Where(f => seen.Add(NamingHelper.ToPascalCase(f.HclName)))
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}.Generated;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Packer {model.PluginKind} type: <c>{model.TypeName}</c>.");
        sb.AppendLine($"/// Scraped from <c>{model.Repo}/{model.SourcePath}</c>.");
        sb.AppendLine($"/// {fields.Count} fields.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public sealed partial class {className}");
        sb.AppendLine("{");

        // Static type name
        sb.AppendLine($"    public static string PluginType => \"{model.TypeName}\";");
        sb.AppendLine();

        // Properties
        foreach (var field in fields)
        {
            var propName = NamingHelper.ToPascalCase(field.HclName);
            var csType = NamingHelper.CtyTypeToCSharp(field.CtyType);

            sb.AppendLine($"    /// <summary>HCL: <c>{field.HclName}</c> ({field.CtyType}){(field.IsRequired ? " [required]" : "")}</summary>");
            sb.AppendLine($"    public {csType} {propName} {{ get; init; }}");
            sb.AppendLine();
        }

        // WriteTo method — emits HCL arguments
        sb.AppendLine($"    /// <summary>Writes all non-null properties as HCL arguments.</summary>");
        sb.AppendLine($"    public void WriteFieldsTo(HclWriter writer)");
        sb.AppendLine("    {");

        foreach (var field in fields)
        {
            var propName = NamingHelper.ToPascalCase(field.HclName);
            var csType = NamingHelper.CtyTypeToCSharp(field.CtyType);

            if (csType == "string?")
                sb.AppendLine($"        writer.Argument(\"{field.HclName}\", {propName});");
            else if (csType == "int?")
                sb.AppendLine($"        writer.Argument(\"{field.HclName}\", {propName});");
            else if (csType == "bool?")
                sb.AppendLine($"        writer.Argument(\"{field.HclName}\", {propName});");
            else if (csType == "List<string>?")
                sb.AppendLine($"        writer.ArgumentList(\"{field.HclName}\", {propName});");
            else if (csType == "List<int>?" || csType == "List<bool>?")
                sb.AppendLine($"        if ({propName} is not null) writer.ArgumentList(\"{field.HclName}\", {propName}.Select(x => x.ToString()).ToList());");
            else if (csType == "List<List<string>>?")
                sb.AppendLine($"        writer.ArgumentListOfLists(\"{field.HclName}\", {propName});");
            else if (csType.StartsWith("Dictionary<string,"))
                sb.AppendLine($"        writer.ArgumentMap(\"{field.HclName}\", {propName});");
            else
                sb.AppendLine($"        writer.Argument(\"{field.HclName}\", {propName});");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
