using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FrenchExDev.Net.BinaryWrapper.SourceGenerator;

/// <summary>
/// Emits {Command}Builder.g.cs — AbstractBuilder&lt;Command&gt; with With*(), Validate*(), Instantiate().
/// </summary>
internal static class BuilderClassEmitter
{
    public static string Emit(DescriptorModel descriptor, UnifiedCommand cmd)
    {
        var dedupedOptions = NamingHelper.DeduplicateOptions(cmd.Options);
        cmd = new UnifiedCommand
        {
            CommandPath = cmd.CommandPath, PathSegments = cmd.PathSegments, Name = cmd.Name,
            Description = cmd.Description, SinceVersion = cmd.SinceVersion, UntilVersion = cmd.UntilVersion,
            Options = dedupedOptions, Arguments = cmd.Arguments
        };
        var commandClassName = NamingHelper.CommandClassName(descriptor.BinaryName, cmd);
        var builderClassName = NamingHelper.BuilderClassName(descriptor.BinaryName, cmd);
        var ns = descriptor.Namespace;
        var commandPath = cmd.PathSegments.Count > 1
            ? string.Join(".", cmd.PathSegments.Skip(1))
            : cmd.Name;

        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine($"public partial class {builderClassName} :");
        sb.AppendLine($"    global::FrenchExDev.Net.Builder.AbstractBuilder<");
        sb.AppendLine($"        global::{(string.IsNullOrEmpty(ns) ? "" : ns + ".")}{commandClassName}>");
        sb.AppendLine("{");

        // Constructor with optional detected version
        sb.AppendLine($"    private readonly global::FrenchExDev.Net.BinaryWrapper.SemanticVersion? _detectedVersion;");
        sb.AppendLine();
        sb.AppendLine($"    public {builderClassName}(global::FrenchExDev.Net.BinaryWrapper.SemanticVersion? detectedVersion = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        _detectedVersion = detectedVersion;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ── Input properties ────────────────────────────────────────────
        sb.AppendLine("    // ── Input properties ────────────────────────────────────────");
        foreach (var opt in cmd.Options)
        {
            var propName = NamingHelper.ToPascalCase(opt.LongName);
            var clrType = NamingHelper.MapClrType(opt.ClrType);

            if (string.Equals(opt.ValueKind, "multiple", StringComparison.OrdinalIgnoreCase))
                sb.AppendLine($"    protected global::System.Collections.Generic.List<{clrType}>? {propName} {{ get; private set; }}");
            else
                sb.AppendLine($"    protected {NamingHelper.NullableType(clrType)} {propName} {{ get; private set; }}");
        }

        foreach (var arg in cmd.Arguments)
        {
            var propName = NamingHelper.ToPascalCase(arg.Name);
            var clrType = NamingHelper.MapClrType(arg.ClrType);

            if (arg.IsVariadic)
                sb.AppendLine($"    protected global::System.Collections.Generic.List<{clrType}>? {propName} {{ get; private set; }}");
            else
                sb.AppendLine($"    protected {NamingHelper.NullableType(clrType)} {propName} {{ get; private set; }}");
        }

        sb.AppendLine();

        // ── With*() fluent methods ──────────────────────────────────────
        sb.AppendLine("    // ── With*() fluent methods ─────────────────────────────────");
        foreach (var opt in cmd.Options)
        {
            var propName = NamingHelper.ToPascalCase(opt.LongName);
            var clrType = NamingHelper.MapClrType(opt.ClrType);
            var isMultiple = string.Equals(opt.ValueKind, "multiple", StringComparison.OrdinalIgnoreCase);
            var paramType = isMultiple
                ? $"global::System.Collections.Generic.List<{clrType}>?"
                : NamingHelper.NullableType(clrType);

            // Version attributes on method
            if (opt.SinceVersion is not null)
                sb.AppendLine($"    [global::FrenchExDev.Net.BinaryWrapper.SinceVersion(\"{opt.SinceVersion}\")]");
            if (opt.UntilVersion is not null)
                sb.AppendLine($"    [global::FrenchExDev.Net.BinaryWrapper.UntilVersion(\"{opt.UntilVersion}\")]");

            sb.AppendLine($"    public {builderClassName} With{propName}({paramType} value)");
            sb.AppendLine("    {");

            // Version guard
            if (opt.SinceVersion is not null || opt.UntilVersion is not null)
            {
                sb.Append("        global::FrenchExDev.Net.BinaryWrapper.VersionGuard.EnsureOptionSupported(");
                sb.Append($"_detectedVersion, \"{NamingHelper.EscapeString(commandPath)}\", \"{NamingHelper.EscapeString(opt.LongName)}\", ");
                sb.Append(opt.SinceVersion is not null ? NamingHelper.SemanticVersionCtor(opt.SinceVersion) : "null");
                sb.Append(", ");
                sb.Append(opt.UntilVersion is not null ? NamingHelper.SemanticVersionCtor(opt.UntilVersion) : "null");
                sb.AppendLine(");");
            }

            sb.AppendLine($"        {propName} = value;");
            sb.AppendLine($"        return this;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        foreach (var arg in cmd.Arguments)
        {
            var propName = NamingHelper.ToPascalCase(arg.Name);
            var clrType = NamingHelper.MapClrType(arg.ClrType);
            var isVariadic = arg.IsVariadic;
            var paramType = isVariadic
                ? $"global::System.Collections.Generic.List<{clrType}>?"
                : NamingHelper.NullableType(clrType);

            sb.AppendLine($"    public {builderClassName} With{propName}({paramType} value)");
            sb.AppendLine("    {");
            sb.AppendLine($"        {propName} = value;");
            sb.AppendLine($"        return this;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // ── Per-property validation ─────────────────────────────────────
        sb.AppendLine("    // ── Per-property validation (virtual, overridable) ─────────");
        foreach (var opt in cmd.Options)
        {
            var propName = NamingHelper.ToPascalCase(opt.LongName);
            var clrType = NamingHelper.MapClrType(opt.ClrType);
            var isMultiple = string.Equals(opt.ValueKind, "multiple", StringComparison.OrdinalIgnoreCase);
            var paramType = isMultiple
                ? $"global::System.Collections.Generic.List<{clrType}>?"
                : NamingHelper.NullableType(clrType);

            sb.AppendLine($"    protected virtual global::System.Collections.Generic.IEnumerable<global::System.Exception>? Validate{propName}({paramType} value) => null;");

            if (isMultiple)
                sb.AppendLine($"    protected virtual global::System.Collections.Generic.IEnumerable<global::System.Exception>? Validate{propName}Item({clrType} item, int index) => null;");
        }

        foreach (var arg in cmd.Arguments)
        {
            var propName = NamingHelper.ToPascalCase(arg.Name);
            var clrType = NamingHelper.MapClrType(arg.ClrType);
            var isVariadic = arg.IsVariadic;
            var paramType = isVariadic
                ? $"global::System.Collections.Generic.List<{clrType}>?"
                : NamingHelper.NullableType(clrType);

            sb.AppendLine($"    protected virtual global::System.Collections.Generic.IEnumerable<global::System.Exception>? Validate{propName}({paramType} value) => null;");

            if (isVariadic)
                sb.AppendLine($"    protected virtual global::System.Collections.Generic.IEnumerable<global::System.Exception>? Validate{propName}Item({clrType} item, int index) => null;");
        }

        sb.AppendLine();

        // ── ValidateAsync ───────────────────────────────────────────────
        sb.AppendLine("    // ── ValidateAsync ─────────────────────────────────────────");
        sb.AppendLine("    protected override global::System.Threading.Tasks.Task<");
        sb.AppendLine("        global::FrenchExDev.Net.Result.Result<");
        sb.AppendLine("            global::FrenchExDev.Net.Builder.ValidationResult>> ValidateAsync(");
        sb.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var __result = new global::FrenchExDev.Net.Builder.ValidationResult();");
        sb.AppendLine($"        var __type = typeof({builderClassName});");
        sb.AppendLine();

        EmitValidateBody(sb, cmd);

        sb.AppendLine("        return global::System.Threading.Tasks.Task.FromResult(");
        sb.AppendLine("            global::FrenchExDev.Net.Result.Result<");
        sb.AppendLine("                global::FrenchExDev.Net.Builder.ValidationResult>.Success(__result));");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ── BuildException ──────────────────────────────────────────────
        sb.AppendLine("    // ── BuildException ────────────────────────────────────────");
        sb.AppendLine("    protected override global::System.Exception BuildException(");
        sb.AppendLine("        global::FrenchExDev.Net.Result.Result<");
        sb.AppendLine("            global::FrenchExDev.Net.Builder.ValidationResult> validationResult)");
        sb.AppendLine("        => new global::System.InvalidOperationException(");
        sb.AppendLine("            validationResult.ValueOrThrow().ToDataAnnotationsValidationResult().ErrorMessage);");
        sb.AppendLine();

        // ── Instantiate ─────────────────────────────────────────────────
        EmitInstantiate(sb, descriptor, cmd, commandClassName, builderClassName, ns);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitValidateBody(StringBuilder sb, UnifiedCommand cmd)
    {
        foreach (var opt in cmd.Options)
        {
            var propName = NamingHelper.ToPascalCase(opt.LongName);
            var isMultiple = string.Equals(opt.ValueKind, "multiple", StringComparison.OrdinalIgnoreCase);

            sb.AppendLine($"        foreach (var __err in Validate{propName}({propName}) ?? global::System.Array.Empty<global::System.Exception>())");
            sb.AppendLine($"            __result.AddError(new global::FrenchExDev.Net.Builder.MemberName(nameof({propName}), __type), __err);");

            if (isMultiple)
            {
                sb.AppendLine($"        if ({propName} is not null)");
                sb.AppendLine("        {");
                sb.AppendLine($"            var __{propName}Idx = 0;");
                sb.AppendLine($"            foreach (var __{propName}Item in {propName})");
                sb.AppendLine("            {");
                sb.AppendLine($"                foreach (var __err in Validate{propName}Item(__{propName}Item, __{propName}Idx) ?? global::System.Array.Empty<global::System.Exception>())");
                sb.AppendLine($"                    __result.AddError(new global::FrenchExDev.Net.Builder.MemberName($\"{{nameof({propName})}}[{{__{propName}Idx}}]\", __type), __err);");
                sb.AppendLine($"                __{propName}Idx++;");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
            }
        }

        foreach (var arg in cmd.Arguments)
        {
            var propName = NamingHelper.ToPascalCase(arg.Name);
            var isVariadic = arg.IsVariadic;

            sb.AppendLine($"        foreach (var __err in Validate{propName}({propName}) ?? global::System.Array.Empty<global::System.Exception>())");
            sb.AppendLine($"            __result.AddError(new global::FrenchExDev.Net.Builder.MemberName(nameof({propName}), __type), __err);");

            if (isVariadic)
            {
                sb.AppendLine($"        if ({propName} is not null)");
                sb.AppendLine("        {");
                sb.AppendLine($"            var __{propName}Idx = 0;");
                sb.AppendLine($"            foreach (var __{propName}Item in {propName})");
                sb.AppendLine("            {");
                sb.AppendLine($"                foreach (var __err in Validate{propName}Item(__{propName}Item, __{propName}Idx) ?? global::System.Array.Empty<global::System.Exception>())");
                sb.AppendLine($"                    __result.AddError(new global::FrenchExDev.Net.Builder.MemberName($\"{{nameof({propName})}}[{{__{propName}Idx}}]\", __type), __err);");
                sb.AppendLine($"                __{propName}Idx++;");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
            }
        }

        sb.AppendLine();
    }

    private static void EmitInstantiate(StringBuilder sb, DescriptorModel descriptor,
        UnifiedCommand cmd, string commandClassName, string builderClassName, string ns)
    {
        var fullCommandType = $"global::{(string.IsNullOrEmpty(ns) ? "" : ns + ".")}{commandClassName}";

        sb.AppendLine("    // ── Instantiate (sealed bridge) ───────────────────────────");
        sb.AppendLine("    protected sealed override async global::System.Threading.Tasks.Task<");
        sb.AppendLine("        global::FrenchExDev.Net.Result.Result<");
        sb.AppendLine($"            global::FrenchExDev.Net.Builder.Reference<{fullCommandType}>>> Instantiate(");
        sb.AppendLine($"        global::FrenchExDev.Net.Builder.Reference<{fullCommandType}> reference,");
        sb.AppendLine("        global::FrenchExDev.Net.Builder.VisitedObjects visitedObjects,");
        sb.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var __value = new {fullCommandType}");
        sb.AppendLine("        {");

        foreach (var opt in cmd.Options)
        {
            var propName = NamingHelper.ToPascalCase(opt.LongName);
            var isMultiple = string.Equals(opt.ValueKind, "multiple", StringComparison.OrdinalIgnoreCase);

            if (isMultiple)
                sb.AppendLine($"            {propName} = {propName}?.AsReadOnly(),");
            else
                sb.AppendLine($"            {propName} = {propName},");
        }

        foreach (var arg in cmd.Arguments)
        {
            var propName = NamingHelper.ToPascalCase(arg.Name);
            if (arg.IsVariadic)
                sb.AppendLine($"            {propName} = {propName}?.AsReadOnly(),");
            else
                sb.AppendLine($"            {propName} = {propName},");
        }

        sb.AppendLine("        };");
        sb.AppendLine("        reference.Resolve(__value);");
        sb.AppendLine("        return global::FrenchExDev.Net.Result.Result<");
        sb.AppendLine($"            global::FrenchExDev.Net.Builder.Reference<{fullCommandType}>>.Success(reference);");
        sb.AppendLine("    }");
    }
}
