using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FrenchExDev.Net.BinaryWrapper.SourceGenerator;

/// <summary>
/// Emits {Binary}Client.g.cs — static entry point with Detect() + per-command Action&lt;Builder&gt; methods.
/// Handles nested command groups as inner classes.
/// </summary>
internal static class ClientClassEmitter
{
    public static string Emit(DescriptorModel descriptor, UnifiedCommandTree unifiedTree)
    {
        var binaryName = descriptor.BinaryName;
        var ns = descriptor.Namespace;
        var clientClassName = NamingHelper.ClientClassName(binaryName);
        var entryClassName = NamingHelper.EntryClassName(binaryName);

        // Build a tree of command groups
        var groups = BuildGroupTree(unifiedTree.Commands, binaryName);

        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        // ── Static entry point class ────────────────────────────────────
        sb.AppendLine($"/// <summary>Static entry point for the {NamingHelper.ToPascalCase(binaryName)} binary wrapper.</summary>");
        sb.AppendLine($"public static partial class {entryClassName}");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Detects the installed binary and returns a typed client.</summary>");
        sb.AppendLine($"    public static {clientClassName} Create(global::FrenchExDev.Net.BinaryWrapper.BinaryBinding binding)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {clientClassName}(binding);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // ── Client class ────────────────────────────────────────────────
        sb.AppendLine($"/// <summary>Typed client for the {NamingHelper.ToPascalCase(binaryName)} binary.</summary>");
        sb.AppendLine($"public partial class {clientClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::FrenchExDev.Net.BinaryWrapper.BinaryBinding _binding;");
        sb.AppendLine("    private readonly global::FrenchExDev.Net.BinaryWrapper.SemanticVersion? _detectedVersion;");
        sb.AppendLine();
        sb.AppendLine($"    public {clientClassName}(global::FrenchExDev.Net.BinaryWrapper.BinaryBinding binding)");
        sb.AppendLine("    {");
        sb.AppendLine("        _binding = binding;");
        sb.AppendLine("        _detectedVersion = binding.DetectedVersion;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Remove leaf commands that clash with sub-group names (e.g., when some versions
        // have "box" as a leaf but others expand it into "box add", "box list", etc.)
        PruneClashingLeaves(groups);

        // Emit leaf command methods and group properties for the root level
        EmitGroupMembers(sb, groups, descriptor, "    ", clientClassName);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitGroupMembers(StringBuilder sb, CommandGroup group,
        DescriptorModel descriptor, string indent, string clientClassName,
        bool isRoot = true)
    {
        // Emit leaf command methods
        foreach (var cmd in group.LeafCommands)
        {
            var commandClassName = NamingHelper.CommandClassName(descriptor.BinaryName, cmd);
            var builderClassName = NamingHelper.BuilderClassName(descriptor.BinaryName, cmd);
            var methodName = NamingHelper.ToPascalCase(cmd.Name);
            var commandPath = cmd.PathSegments.Count > 1
                ? string.Join(".", cmd.PathSegments.Skip(1))
                : cmd.Name;

            if (cmd.Description is not null)
                sb.AppendLine($"{indent}/// <summary>{EscapeXml(cmd.Description)}</summary>");

            if (cmd.SinceVersion is not null)
                sb.AppendLine($"{indent}[global::FrenchExDev.Net.BinaryWrapper.SinceVersion(\"{cmd.SinceVersion}\")]");
            if (cmd.UntilVersion is not null)
                sb.AppendLine($"{indent}[global::FrenchExDev.Net.BinaryWrapper.UntilVersion(\"{cmd.UntilVersion}\")]");

            sb.AppendLine($"{indent}public {commandClassName} {methodName}(global::System.Action<{builderClassName}> configure)");
            sb.AppendLine($"{indent}{{");

            // Version guard on command
            if (cmd.SinceVersion is not null || cmd.UntilVersion is not null)
            {
                sb.Append($"{indent}    global::FrenchExDev.Net.BinaryWrapper.VersionGuard.EnsureCommandSupported(");
                sb.Append($"_detectedVersion, \"{NamingHelper.EscapeString(commandPath)}\", ");
                sb.Append(cmd.SinceVersion is not null ? NamingHelper.SemanticVersionCtor(cmd.SinceVersion) : "null");
                sb.Append(", ");
                sb.Append(cmd.UntilVersion is not null ? NamingHelper.SemanticVersionCtor(cmd.UntilVersion) : "null");
                sb.AppendLine(");");
            }

            sb.AppendLine($"{indent}    var __builder = new {builderClassName}(_detectedVersion);");
            sb.AppendLine($"{indent}    configure(__builder);");
            sb.AppendLine($"{indent}    return __builder.BuildAsync().GetAwaiter().GetResult().ValueOrThrow().Resolved();");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();
        }

        // Emit sub-group properties
        foreach (var subGroup in group.SubGroups)
        {
            var groupPropName = NamingHelper.ToPascalCase(subGroup.Key);
            var innerClassName = clientClassName + NamingHelper.ToPascalCase(subGroup.Key) + "Group";

            sb.AppendLine($"{indent}/// <summary>{groupPropName} command group.</summary>");
            var ctorArg = isRoot ? "this" : "_client";
            sb.AppendLine($"{indent}public {innerClassName} {groupPropName} => new {innerClassName}({ctorArg});");
            sb.AppendLine();

            // Emit inner class
            sb.AppendLine($"{indent}public partial class {innerClassName}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    private readonly {clientClassName} _client;");
            sb.AppendLine($"{indent}    internal {innerClassName}({clientClassName} client) => _client = client;");
            sb.AppendLine($"{indent}    private global::FrenchExDev.Net.BinaryWrapper.SemanticVersion? _detectedVersion => _client._detectedVersion;");
            sb.AppendLine();

            EmitGroupMembers(sb, subGroup.Value, descriptor, indent + "    ", clientClassName, isRoot: false);

            sb.AppendLine($"{indent}}}");
            sb.AppendLine();
        }
    }

    private static CommandGroup BuildGroupTree(List<UnifiedCommand> commands, string binaryName)
    {
        var root = new CommandGroup();

        foreach (var cmd in commands)
        {
            // Path segments after binary name
            var segments = cmd.PathSegments.Count > 1
                ? cmd.PathSegments.GetRange(1, cmd.PathSegments.Count - 1)
                : new List<string> { cmd.Name };

            if (segments.Count == 1)
            {
                root.LeafCommands.Add(cmd);
            }
            else
            {
                // Navigate to the right group
                var current = root;
                for (var i = 0; i < segments.Count - 1; i++)
                {
                    var seg = segments[i];
                    if (!current.SubGroups.TryGetValue(seg, out var sub))
                    {
                        sub = new CommandGroup();
                        current.SubGroups[seg] = sub;
                    }
                    current = sub;
                }
                current.LeafCommands.Add(cmd);
            }
        }

        return root;
    }

    private sealed class CommandGroup
    {
        public List<UnifiedCommand> LeafCommands { get; } = new();
        public Dictionary<string, CommandGroup> SubGroups { get; } = new(StringComparer.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Removes leaf commands whose name clashes with a sub-group at the same level.
    /// This happens when some versions expose a command as a leaf (no sub-commands scraped)
    /// while later versions expand it into a group with sub-commands.
    /// </summary>
    private static void PruneClashingLeaves(CommandGroup group)
    {
        group.LeafCommands.RemoveAll(cmd =>
            group.SubGroups.ContainsKey(cmd.Name));

        foreach (var sub in group.SubGroups.Values)
            PruneClashingLeaves(sub);
    }

    private static string EscapeXml(string text) =>
        text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
