using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FrenchExDev.Net.BinaryWrapper.SourceGenerator;

/// <summary>
/// Emits {Command}.g.cs — sealed ICliCommand product class with init properties + ToArguments().
/// </summary>
internal static class CommandClassEmitter
{
    public static string Emit(DescriptorModel descriptor, UnifiedCommand cmd)
    {
        var className = NamingHelper.CommandClassName(descriptor.BinaryName, cmd);
        var ns = descriptor.Namespace;
        var flagPrefix = descriptor.FlagPrefix;
        var flagValueSeparator = descriptor.FlagValueSeparator;
        var dedupedOptions = NamingHelper.DeduplicateOptions(cmd.Options);
        cmd = new UnifiedCommand
        {
            CommandPath = cmd.CommandPath, PathSegments = cmd.PathSegments, Name = cmd.Name,
            Description = cmd.Description, SinceVersion = cmd.SinceVersion, UntilVersion = cmd.UntilVersion,
            Options = dedupedOptions, Arguments = cmd.Arguments
        };
        var useBoolEquals = descriptor.UseBoolEqualsFormat;
        // Command path segments after the binary name
        var commandSegments = cmd.PathSegments.Count > 1
            ? cmd.PathSegments.GetRange(1, cmd.PathSegments.Count - 1)
            : new List<string>();

        var sb = new StringBuilder(2048);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        // XML doc
        if (cmd.Description is not null)
        {
            sb.AppendLine($"/// <summary>{EscapeXml(cmd.Description)}</summary>");
        }

        // Version attributes
        if (cmd.SinceVersion is not null)
            sb.AppendLine($"[global::FrenchExDev.Net.BinaryWrapper.SinceVersion(\"{cmd.SinceVersion}\")]");
        if (cmd.UntilVersion is not null)
            sb.AppendLine($"[global::FrenchExDev.Net.BinaryWrapper.UntilVersion(\"{cmd.UntilVersion}\")]");

        sb.AppendLine($"public sealed partial class {className} : global::FrenchExDev.Net.BinaryWrapper.ICliCommand");
        sb.AppendLine("{");

        // Properties from options
        foreach (var opt in cmd.Options)
        {
            var propName = NamingHelper.ToPascalCase(opt.LongName);
            var clrType = NamingHelper.MapClrType(opt.ClrType);

            if (opt.SinceVersion is not null)
                sb.AppendLine($"    [global::FrenchExDev.Net.BinaryWrapper.SinceVersion(\"{opt.SinceVersion}\")]");
            if (opt.UntilVersion is not null)
                sb.AppendLine($"    [global::FrenchExDev.Net.BinaryWrapper.UntilVersion(\"{opt.UntilVersion}\")]");

            if (string.Equals(opt.ValueKind, "multiple", StringComparison.OrdinalIgnoreCase))
            {
                sb.AppendLine($"    public global::System.Collections.Generic.IReadOnlyList<{clrType}>? {propName} {{ get; init; }}");
            }
            else
            {
                sb.AppendLine($"    public {NamingHelper.NullableType(clrType)} {propName} {{ get; init; }}");
            }
        }

        // Properties from arguments
        foreach (var arg in cmd.Arguments)
        {
            var propName = NamingHelper.ToPascalCase(arg.Name);
            var clrType = NamingHelper.MapClrType(arg.ClrType);

            if (arg.IsVariadic)
                sb.AppendLine($"    public global::System.Collections.Generic.IReadOnlyList<{clrType}>? {propName} {{ get; init; }}");
            else
                sb.AppendLine($"    public {NamingHelper.NullableType(clrType)} {propName} {{ get; init; }}");
        }

        sb.AppendLine();

        // CommandPath property
        sb.Append("    public global::System.Collections.Generic.IReadOnlyList<string> CommandPath => new[] { ");
        sb.Append(string.Join(", ", commandSegments.Select(s => $"\"{NamingHelper.EscapeString(s)}\"")));
        sb.AppendLine(" };");
        sb.AppendLine();

        // ToArguments method
        sb.AppendLine("    public global::System.Collections.Generic.IReadOnlyList<string> ToArguments()");
        sb.AppendLine("    {");
        sb.AppendLine("        var __args = new global::System.Collections.Generic.List<string>();");

        foreach (var opt in cmd.Options)
        {
            var propName = NamingHelper.ToPascalCase(opt.LongName);
            var clrType = NamingHelper.MapClrType(opt.ClrType);
            var rawName = opt.LongName.Replace("[", "").Replace("]", "");
            var spIdx = rawName.IndexOf(' ');
            var sanitizedName = spIdx > 0 ? rawName.Substring(0, spIdx) : rawName;
            var flagName = $"{flagPrefix}{sanitizedName}";

            if (string.Equals(opt.ValueKind, "multiple", StringComparison.OrdinalIgnoreCase))
            {
                sb.AppendLine($"        if ({propName} is not null)");
                sb.AppendLine($"            foreach (var __v in {propName})");
                if (flagValueSeparator == "=")
                    sb.AppendLine($"                __args.Add(\"{NamingHelper.EscapeString(flagName)}=\" + __v);");
                else
                {
                    sb.AppendLine($"            {{");
                    sb.AppendLine($"                __args.Add(\"{NamingHelper.EscapeString(flagName)}\");");
                    sb.AppendLine($"                __args.Add(__v?.ToString() ?? \"\");");
                    sb.AppendLine($"            }}");
                }
            }
            else if (string.Equals(opt.ValueKind, "flag", StringComparison.OrdinalIgnoreCase))
            {
                if (useBoolEquals)
                {
                    sb.AppendLine($"        if ({propName}.HasValue)");
                    sb.AppendLine($"            __args.Add(\"{NamingHelper.EscapeString(flagName)}=\" + ({propName}.Value ? \"true\" : \"false\"));");
                }
                else
                {
                    sb.AppendLine($"        if ({propName} == true)");
                    sb.AppendLine($"            __args.Add(\"{NamingHelper.EscapeString(flagName)}\");");
                }
            }
            else // single value
            {
                if (clrType == "string")
                {
                    sb.AppendLine($"        if ({propName} is not null)");
                }
                else
                {
                    sb.AppendLine($"        if ({propName}.HasValue)");
                }

                if (flagValueSeparator == "=")
                    sb.AppendLine($"            __args.Add(\"{NamingHelper.EscapeString(flagName)}=\" + {propName});");
                else
                {
                    sb.AppendLine($"        {{");
                    sb.AppendLine($"            __args.Add(\"{NamingHelper.EscapeString(flagName)}\");");
                    sb.AppendLine($"            __args.Add({propName}?.ToString() ?? \"\");");
                    sb.AppendLine($"        }}");
                }
            }
        }

        // Positional arguments at the end
        foreach (var arg in cmd.Arguments)
        {
            var propName = NamingHelper.ToPascalCase(arg.Name);
            if (arg.IsVariadic)
            {
                sb.AppendLine($"        if ({propName} is not null)");
                sb.AppendLine($"            foreach (var __v in {propName})");
                sb.AppendLine($"                __args.Add(__v?.ToString() ?? \"\");");
            }
            else
            {
                sb.AppendLine($"        if ({propName} is not null)");
                sb.AppendLine($"            __args.Add({propName}?.ToString() ?? \"\");");
            }
        }

        sb.AppendLine("        return __args;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EscapeXml(string text) =>
        text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
