<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsCheck" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FrenchExDev.Net.BinaryWrapper\FrenchExDev.Net.BinaryWrapper.csproj" />
    <ProjectReference Include="..\FrenchExDev.Net.BinaryWrapper.Design\FrenchExDev.Net.BinaryWrapper.Design.csproj" />
  </ItemGroup>

</Project>
