using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Threading;

namespace FrenchExDev.Net.Builder.SourceGenerator;

[Generator]
public sealed class BuilderGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "FrenchExDev.Net.Builder.Attributes.BuilderAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => GetModel(ctx, ct))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(models, static (ctx, model) =>
        {
            var source = GenerateSource(model!);
            ctx.AddSource($"{model!.ClassName}Builder.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    // ── Model extraction ──────────────────────────────────────────────────────

    private static BuilderModel? GetModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol)
            return null;

        ct.ThrowIfCancellationRequested();

        // Read optional Exception named argument from [Builder(Exception = typeof(...))]
        string? exceptionFull = null;
        var attr = ctx.Attributes[0];
        foreach (var arg in attr.NamedArguments)
        {
            if (arg.Key == "Exception" && arg.Value.Value is INamedTypeSymbol exType)
            {
                exceptionFull = exType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                break;
            }
        }

        // Collect public, non-static, settable instance properties
        var properties = new List<PropertyModel>();
        foreach (var member in classSymbol.GetMembers())
        {
            ct.ThrowIfCancellationRequested();
            if (member is not IPropertySymbol prop) continue;
            if (prop.IsStatic || prop.IsAbstract || prop.IsIndexer) continue;
            if (prop.DeclaredAccessibility != Accessibility.Public) continue;
            if (prop.SetMethod is null) continue;
            if (prop.SetMethod.DeclaredAccessibility != Accessibility.Public) continue;
            if (prop.GetMethod is null) continue;

            var typeFull = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var nullableTypeFull = GetNullableTypeFull(prop.Type, typeFull);
            var (isCollection, itemTypeFull) = GetCollectionInfo(prop.Type);

            properties.Add(new PropertyModel(prop.Name, typeFull, nullableTypeFull, isCollection, itemTypeFull));
        }

        var ns = classSymbol.ContainingNamespace is { IsGlobalNamespace: false } nsSym
            ? nsSym.ToDisplayString()
            : string.Empty;

        return new BuilderModel(ns, classSymbol.Name, exceptionFull, properties);
    }

    private static string GetNullableTypeFull(ITypeSymbol type, string typeFull)
    {
        if (type.IsValueType)
        {
            // Already Nullable<T> (e.g. int?) — keep as-is
            if (type is INamedTypeSymbol nt &&
                nt.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
                return typeFull;

            return typeFull + "?";
        }

        // Reference type or array → add ?
        return typeFull + "?";
    }

    private static (bool IsCollection, string? ItemTypeFull) GetCollectionInfo(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol arr)
            return (true, arr.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));

        if (type is INamedTypeSymbol named && named.IsGenericType && named.TypeArguments.Length == 1)
        {
            var ns = named.OriginalDefinition.ContainingNamespace?.ToDisplayString() ?? string.Empty;
            var meta = named.OriginalDefinition.MetadataName;

            if (ns == "System.Collections.Generic" &&
                (meta == "IEnumerable`1" || meta == "ICollection`1" || meta == "IList`1" ||
                 meta == "List`1" || meta == "IReadOnlyList`1" || meta == "IReadOnlyCollection`1"))
            {
                return (true, named.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            }
        }

        return (false, null);
    }

    // ── Code generation ───────────────────────────────────────────────────────

    private static string GenerateSource(BuilderModel model)
    {
        var sb = new StringBuilder(4096);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        var classRef = string.IsNullOrEmpty(model.Namespace)
            ? $"global::{model.ClassName}"
            : $"global::{model.Namespace}.{model.ClassName}";

        var baseClass = model.ExceptionFullName is not null
            ? $"global::FrenchExDev.Net.Builder.AbstractBuilder<{classRef}, {model.ExceptionFullName}>"
            : $"global::FrenchExDev.Net.Builder.AbstractBuilder<{classRef}>";

        sb.AppendLine($"public partial class {model.ClassName}Builder : {baseClass}");
        sb.AppendLine("{");

        AppendInputProperties(sb, model);
        AppendValidationMethods(sb, model);
        AppendValidateAsync(sb, model);
        AppendBuildException(sb, model);
        AppendInstantiate(sb, model, classRef);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendInputProperties(StringBuilder sb, BuilderModel model)
    {
        var builderName = $"{model.ClassName}Builder";
        sb.AppendLine("    // ── Input properties ─────────────────────────────────────────────");
        foreach (var prop in model.Properties)
        {
            sb.AppendLine($"    protected {prop.NullableTypeFull} {prop.Name} {{ get; private set; }}");
            sb.AppendLine($"    public {builderName} With{prop.Name}({prop.NullableTypeFull} value) {{ {prop.Name} = value; return this; }}");
        }
        sb.AppendLine();
    }

    private static void AppendValidationMethods(StringBuilder sb, BuilderModel model)
    {
        if (model.Properties.Count == 0) return;

        sb.AppendLine("    // ── Per-property validation (virtual, overridable) ────────────────");
        foreach (var prop in model.Properties)
        {
            sb.AppendLine(
                $"    protected virtual global::System.Collections.Generic.IEnumerable<global::System.Exception>?" +
                $" Validate{prop.Name}({prop.NullableTypeFull} value) => null;");

            if (prop.IsCollection && prop.ItemTypeFull is not null)
                sb.AppendLine(
                    $"    protected virtual global::System.Collections.Generic.IEnumerable<global::System.Exception>?" +
                    $" Validate{prop.Name}Item({prop.ItemTypeFull} item, int index) => null;");
        }
        sb.AppendLine();
    }

    private static void AppendValidateAsync(StringBuilder sb, BuilderModel model)
    {
        const string VR = "global::FrenchExDev.Net.Builder.ValidationResult";
        const string ResultVR = "global::FrenchExDev.Net.Result.Result<global::FrenchExDev.Net.Builder.ValidationResult>";
        const string EmptyErr = "global::System.Array.Empty<global::System.Exception>()";
        const string MemberName = "global::FrenchExDev.Net.Builder.MemberName";

        sb.AppendLine("    // ── ValidateAsync ─────────────────────────────────────────────────");
        sb.AppendLine($"    protected override global::System.Threading.Tasks.Task<{ResultVR}> ValidateAsync(");
        sb.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var __result = new {VR}();");
        sb.AppendLine($"        var __type = typeof({model.ClassName}Builder);");

        if (model.Properties.Count > 0)
            sb.AppendLine();

        foreach (var prop in model.Properties)
        {
            sb.AppendLine(
                $"        foreach (var __err in Validate{prop.Name}({prop.Name}) ?? {EmptyErr})");
            sb.AppendLine(
                $"            __result.AddError(new {MemberName}(nameof({prop.Name}), __type), __err);");

            if (prop.IsCollection && prop.ItemTypeFull is not null)
            {
                var idxVar = $"__{prop.Name}Idx";
                var itemVar = $"__{prop.Name}Item";
                sb.AppendLine($"        if ({prop.Name} is not null)");
                sb.AppendLine("        {");
                sb.AppendLine($"            var {idxVar} = 0;");
                sb.AppendLine($"            foreach (var {itemVar} in {prop.Name})");
                sb.AppendLine("            {");
                sb.AppendLine(
                    $"                foreach (var __err in Validate{prop.Name}Item({itemVar}, {idxVar}) ?? {EmptyErr})");
                // Produces: $"{nameof(Prop)}[{__PropIdx}]"
                sb.AppendLine(
                    $"                    __result.AddError(new {MemberName}(" +
                    "$\"" + $"{{nameof({prop.Name})}}[{{{idxVar}}}]" + "\", __type), __err);");
                sb.AppendLine($"                {idxVar}++;");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
            }

            sb.AppendLine();
        }

        sb.AppendLine(
            $"        return global::System.Threading.Tasks.Task.FromResult(");
        sb.AppendLine(
            $"            global::FrenchExDev.Net.Result.Result<{VR}>.Success(__result));");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendBuildException(StringBuilder sb, BuilderModel model)
    {
        const string ResultVR = "global::FrenchExDev.Net.Result.Result<global::FrenchExDev.Net.Builder.ValidationResult>";

        sb.AppendLine("    // ── BuildException ───────────────────────────────────────────────");

        if (model.ExceptionFullName is not null)
        {
            sb.AppendLine($"    protected override {model.ExceptionFullName} TypedBuildException(");
            sb.AppendLine($"        {ResultVR} validationResult)");
            sb.AppendLine("        => new(validationResult.ValueOrThrow().ToDataAnnotationsValidationResult().ErrorMessage);");
        }
        else
        {
            sb.AppendLine("    protected override global::System.Exception BuildException(");
            sb.AppendLine($"        {ResultVR} validationResult)");
            sb.AppendLine("        => new global::System.InvalidOperationException(");
            sb.AppendLine("            validationResult.ValueOrThrow().ToDataAnnotationsValidationResult().ErrorMessage);");
        }

        sb.AppendLine();
    }

    private static void AppendInstantiate(StringBuilder sb, BuilderModel model, string classRef)
    {
        var refT = $"global::FrenchExDev.Net.Builder.Reference<{classRef}>";
        var resultRefT = $"global::FrenchExDev.Net.Result.Result<{refT}>";

        sb.AppendLine("    // ── Instantiate (sealed bridge — hides Reference<T>) ─────────────");
        sb.AppendLine($"    protected sealed override async global::System.Threading.Tasks.Task<{resultRefT}> Instantiate(");
        sb.AppendLine($"        {refT} reference,");
        sb.AppendLine("        global::FrenchExDev.Net.Builder.VisitedObjects visitedObjects,");
        sb.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");

        if (model.ExceptionFullName is not null)
        {
            sb.AppendLine("        var __res = await InstantiateAsync(cancellationToken).ConfigureAwait(false);");
            sb.AppendLine("        if (__res.IsFailure)");
            sb.AppendLine($"            return {resultRefT}.Failure(");
            sb.AppendLine("                new global::System.ComponentModel.DataAnnotations.ValidationResult(__res.Error!.Message));");
            sb.AppendLine("        reference.Resolve(__res.Value!);");
        }
        else
        {
            sb.AppendLine("        var __value = await CreateAsync(cancellationToken).ConfigureAwait(false);");
            sb.AppendLine("        reference.Resolve(__value);");
        }

        sb.AppendLine($"        return {resultRefT}.Success(reference);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Developer-facing partial method
        sb.AppendLine("    // ── Developer must implement ─────────────────────────────────────");
        if (model.ExceptionFullName is not null)
        {
            var resultT = $"global::FrenchExDev.Net.Result.Result<{classRef}, {model.ExceptionFullName}>";
            sb.AppendLine($"    protected override partial global::System.Threading.Tasks.Task<{resultT}> InstantiateAsync(");
            sb.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default);");
        }
        else
        {
            sb.AppendLine($"    protected partial global::System.Threading.Tasks.Task<{classRef}> CreateAsync(");
            sb.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default);");
        }
    }
}

// ── Internal models ───────────────────────────────────────────────────────────

internal sealed class BuilderModel
{
    public BuilderModel(
        string ns,
        string className,
        string? exceptionFullName,
        IReadOnlyList<PropertyModel> properties)
    {
        Namespace = ns;
        ClassName = className;
        ExceptionFullName = exceptionFullName;
        Properties = properties;
    }

    public string Namespace { get; }
    public string ClassName { get; }
    public string? ExceptionFullName { get; }
    public IReadOnlyList<PropertyModel> Properties { get; }
}

internal sealed class PropertyModel
{
    public PropertyModel(
        string name,
        string typeFull,
        string nullableTypeFull,
        bool isCollection,
        string? itemTypeFull)
    {
        Name = name;
        TypeFull = typeFull;
        NullableTypeFull = nullableTypeFull;
        IsCollection = isCollection;
        ItemTypeFull = itemTypeFull;
    }

    public string Name { get; }
    public string TypeFull { get; }
    public string NullableTypeFull { get; }
    public bool IsCollection { get; }
    public string? ItemTypeFull { get; }
}
