using System.Collections.Generic;
using System.Text;

namespace FrenchExDev.Net.Traefik.Bundle.SourceGenerator;

internal static class TraefikModelClassEmitter
{
    public static string EmitRootClass(string ns, string className, List<UnifiedProperty> rootProperties)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        sb.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine($"public partial class {className}");
        sb.AppendLine("{");

        foreach (var up in rootProperties)
        {
            var prop = up.Property;
            var type = TraefikNamingHelper.MapCSharpType(prop);

            if (prop.Description is not null)
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {EscapeXml(prop.Description)}");
                sb.AppendLine("    /// </summary>");
            }
            EmitVersionAttributes(sb, up);
            if (prop.IsDeprecated)
                sb.AppendLine("    [global::System.Obsolete(\"Deprecated.\")]");
            sb.AppendLine($"    public {type} {prop.CSharpName} {{ get; set; }}");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    public static IEnumerable<(string FileName, string Source)> EmitDefinitions(
        string ns, UnifiedSchema schema)
    {
        foreach (var kvp in schema.Definitions)
        {
            var defName = kvp.Key;
            var def = kvp.Value;

            var className = TraefikNamingHelper.DefinitionToClassName(defName);

            if (def.IsOneOfDiscriminated && def.Branches is not null)
            {
                // Emit discriminated union as flat class with nullable properties
                var source = EmitDiscriminatedClass(ns, className, def.Description, def.Branches);
                yield return ($"{className}.g.cs", source);
                continue;
            }

            // Emit even empty classes if they're referenced by other definitions

            var classSource = EmitClass(ns, className, def.Description, def.Properties,
                def.SinceVersion, def.UntilVersion);
            yield return ($"{className}.g.cs", classSource);

            // Emit inline object classes found in properties
            foreach (var inline in CollectInlineClasses(ns, def.Properties))
                yield return inline;
        }

        // Collect inline classes from root properties
        foreach (var up in schema.RootProperties)
        {
            var prop = up.Property;
            if (prop.Type == PropertyType.InlineObject &&
                prop.InlineClassName is not null &&
                prop.InlineObjectProperties is not null)
            {
                var source = EmitClass(ns, prop.InlineClassName, null,
                    prop.InlineObjectProperties.ConvertAll(p => new UnifiedProperty { Property = p }),
                    null, null);
                yield return ($"{prop.InlineClassName}.g.cs", source);

                foreach (var nested in CollectInlineClasses(ns,
                    prop.InlineObjectProperties.ConvertAll(p => new UnifiedProperty { Property = p })))
                    yield return nested;
            }
        }
    }

    private static string EmitDiscriminatedClass(string ns, string className,
        string? description, List<DiscriminatedBranch> branches)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        if (description is not null)
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// {EscapeXml(description)}");
            sb.AppendLine("/// </summary>");
        }

        sb.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine("[global::FrenchExDev.Net.Traefik.Bundle.Attributes.TraefikDiscriminatedUnion]");
        sb.AppendLine($"public partial class {className}");
        sb.AppendLine("{");

        foreach (var branch in branches)
        {
            var propName = TraefikNamingHelper.ToPascalCase(branch.PropertyName);
            var refClassName = TraefikNamingHelper.DefinitionToClassName(branch.RefName);
            sb.AppendLine($"    public {refClassName}? {propName} {{ get; set; }}");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static IEnumerable<(string FileName, string Source)> CollectInlineClasses(
        string ns, List<UnifiedProperty> properties)
    {
        foreach (var up in properties)
        {
            var prop = up.Property;

            // Inline object property
            if (prop.Type == PropertyType.InlineObject &&
                prop.InlineClassName is not null &&
                prop.InlineObjectProperties is not null)
            {
                var unifiedProps = prop.InlineObjectProperties
                    .ConvertAll(p => new UnifiedProperty { Property = p });
                var source = EmitClass(ns, prop.InlineClassName, null, unifiedProps, null, null);
                yield return ($"{prop.InlineClassName}.g.cs", source);

                foreach (var nested in CollectInlineClasses(ns, unifiedProps))
                    yield return nested;
            }

            // Array of inline objects
            if (prop.Type == PropertyType.Array &&
                prop.Items?.Type == PropertyType.InlineObject &&
                prop.Items.InlineClassName is not null &&
                prop.Items.InlineObjectProperties is not null)
            {
                var unifiedProps = prop.Items.InlineObjectProperties
                    .ConvertAll(p => new UnifiedProperty { Property = p });
                var source = EmitClass(ns, prop.Items.InlineClassName, null, unifiedProps, null, null);
                yield return ($"{prop.Items.InlineClassName}.g.cs", source);

                foreach (var nested in CollectInlineClasses(ns, unifiedProps))
                    yield return nested;
            }

            // Pattern properties inline classes
            if (prop.Type == PropertyType.PatternPropsInline &&
                prop.PatternPropsInlineClassName is not null &&
                prop.PatternPropsInlineProperties is not null)
            {
                var unifiedProps = prop.PatternPropsInlineProperties
                    .ConvertAll(p => new UnifiedProperty { Property = p });
                var source = EmitClass(ns, prop.PatternPropsInlineClassName, null, unifiedProps, null, null);
                yield return ($"{prop.PatternPropsInlineClassName}.g.cs", source);

                foreach (var nested in CollectInlineClasses(ns, unifiedProps))
                    yield return nested;
            }
        }
    }

    private static string EmitClass(string ns, string className, string? description,
        List<UnifiedProperty> properties, string? sinceVersion, string? untilVersion)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        if (description is not null)
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// {EscapeXml(description)}");
            sb.AppendLine("/// </summary>");
        }

        EmitVersionAttributes(sb, sinceVersion, untilVersion, "");

        sb.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine($"public partial class {className}");
        sb.AppendLine("{");

        foreach (var up in properties)
        {
            var prop = up.Property;
            var type = TraefikNamingHelper.MapCSharpType(prop);

            if (prop.Description is not null)
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {EscapeXml(prop.Description)}");
                sb.AppendLine("    /// </summary>");
            }
            EmitVersionAttributes(sb, up);
            if (prop.IsDeprecated)
                sb.AppendLine("    [global::System.Obsolete(\"Deprecated.\")]");
            sb.AppendLine($"    public {type} {prop.CSharpName} {{ get; set; }}");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitVersionAttributes(StringBuilder sb, UnifiedProperty up)
    {
        EmitVersionAttributes(sb, up.SinceVersion, up.UntilVersion, "    ");
    }

    private static void EmitVersionAttributes(StringBuilder sb, string? since, string? until, string indent)
    {
        if (since is not null)
            sb.AppendLine($"{indent}[SinceVersion(\"{since}\")]");
        if (until is not null)
            sb.AppendLine($"{indent}[UntilVersion(\"{until}\")]");
    }

    private static string EscapeXml(string text)
    {
        return text
            .Replace("\r\n", " ")
            .Replace("\n", " ")
            .Replace("\r", " ")
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
    }
}
