using System.Text;

namespace FrenchExDev.Net.Builder.SourceGenerator.Lib;

/// <summary>
/// Emits a full builder class from a <see cref="BuilderEmitModel"/>.
/// No Roslyn dependency — usable by any source generator targeting netstandard2.0.
/// </summary>
public static class BuilderEmitter
{
    public static string Emit(BuilderEmitModel model)
    {
        var sb = new StringBuilder(4096);

        var classRef = string.IsNullOrEmpty(model.Namespace)
            ? $"global::{model.TargetClassName}"
            : $"global::{model.Namespace}.{model.TargetClassName}";

        EmitFileHeader(sb, model);
        EmitClassHeader(sb, model, classRef);

        AppendInputProperties(sb, model);
        AppendValidationMethods(sb, model);
        AppendValidateAsync(sb, model);
        AppendBuildException(sb, model);
        AppendInstantiate(sb, model, classRef);
        AppendCreateInstance(sb, model, classRef);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitFileHeader(StringBuilder sb, BuilderEmitModel model)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0618 // Obsolete members");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }
    }

    private static void EmitClassHeader(StringBuilder sb, BuilderEmitModel model, string classRef)
    {
        var baseClass = model.ExceptionFullName is not null
            ? $"global::FrenchExDev.Net.Builder.AbstractBuilder<{classRef}, {model.ExceptionFullName}>"
            : $"global::FrenchExDev.Net.Builder.AbstractBuilder<{classRef}>";

        var classModifier = model.Instantiation == "custom" ? "abstract " : "";
        sb.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine($"public {classModifier}partial class {model.BuilderClassName} : {baseClass}");
        sb.AppendLine("{");

        if (model.Preamble is not null)
        {
            sb.AppendLine(model.Preamble);
            sb.AppendLine();
        }
    }

    // ── Shared emission helpers ─────────────────────────────────────────────

    private static void EmitAttributes(StringBuilder sb, BuilderPropertyModel prop)
    {
        if (prop.WithMethodAttributes is null) return;
        foreach (var attr in prop.WithMethodAttributes)
            sb.AppendLine($"    {attr}");
    }

    private static void EmitBodyPrefix(StringBuilder sb, BuilderPropertyModel prop)
    {
        if (prop.WithMethodBodyPrefix is not null)
            sb.AppendLine($"        {prop.WithMethodBodyPrefix}");
    }

    // ── Input properties ────────────────────────────────────────────────────

    private static void AppendInputProperties(StringBuilder sb, BuilderEmitModel model)
    {
        sb.AppendLine("    // ── Input properties ─────────────────────────────────────────────");
        foreach (var prop in model.Properties)
        {
            sb.AppendLine($"    protected {prop.NullableTypeFull} {prop.Name} {{ get; private set; }}");
            AppendWithMethod(sb, model, prop);
            AppendPropertyOverloads(sb, model, prop);
        }
        sb.AppendLine();
    }

    private static void AppendWithMethod(StringBuilder sb, BuilderEmitModel model, BuilderPropertyModel prop)
    {
        EmitAttributes(sb, prop);
        if (prop.WithMethodBodyPrefix is not null)
        {
            sb.AppendLine($"    public {model.BuilderClassName} With{prop.Name}({prop.NullableTypeFull} value)");
            sb.AppendLine("    {");
            sb.AppendLine($"        {prop.WithMethodBodyPrefix}");
            sb.AppendLine($"        {prop.Name} = value;");
            sb.AppendLine("        return this;");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine($"    public {model.BuilderClassName} With{prop.Name}({prop.NullableTypeFull} value) {{ {prop.Name} = value; return this; }}");
        }
    }

    private static void AppendPropertyOverloads(StringBuilder sb, BuilderEmitModel model, BuilderPropertyModel prop)
    {
        if (prop.IsDictionary && prop.DictKeyTypeFull is not null && prop.DictValueTypeFull is not null)
            AppendDictionaryOverloads(sb, model, prop);

        if (prop.IsCollection && prop.ItemTypeFull is not null && prop.CollectionSingularName is not null)
        {
            if (prop.ItemBuilderClassName is not null)
                AppendListBuilderOverloads(sb, model, prop);
            else
                AppendListSimpleOverload(sb, model, prop);
        }
    }

    // ── Dictionary helpers ──────────────────────────────────────────────────

    private static string? GetDictBuilderFieldName(BuilderPropertyModel prop)
    {
        if (!prop.IsDictionary || prop.DictValueBuilderClassName is null)
            return null;
        return $"__{prop.Name}Builder";
    }

    private static string GetDictBuilderType(BuilderPropertyModel prop)
    {
        const string DictBuilder = "global::FrenchExDev.Net.Builder.DictionaryBuilder";
        var valueType = prop.DictValueTypeFull!.TrimEnd('?');
        return $"{DictBuilder}<{prop.DictKeyTypeFull}, {valueType}, {prop.DictValueBuilderClassName}>";
    }

    private static void AppendDictionaryOverloads(StringBuilder sb, BuilderEmitModel model, BuilderPropertyModel prop)
    {
        const string DictBuilder = "global::FrenchExDev.Net.Builder.DictionaryBuilder";

        var hasValueBuilder = prop.DictValueBuilderClassName is not null;
        var builderFieldName = GetDictBuilderFieldName(prop);
        var dictBuilderType = hasValueBuilder
            ? GetDictBuilderType(prop)
            : $"{DictBuilder}<{prop.DictKeyTypeFull}, {prop.DictValueTypeFull}>";

        if (builderFieldName is not null)
            sb.AppendLine($"    private {dictBuilderType}? {builderFieldName};");

        AppendDictBulkOverload(sb, model, prop, dictBuilderType, builderFieldName);

        if (prop.DictSingularName is not null && builderFieldName is not null)
            AppendDictBuilderSingular(sb, model, prop, dictBuilderType, builderFieldName);

        if (prop.DictSingularName is not null && !hasValueBuilder)
            AppendDictSimpleSingular(sb, model, prop);
    }

    private static void AppendDictBulkOverload(StringBuilder sb, BuilderEmitModel model, BuilderPropertyModel prop,
        string dictBuilderType, string? builderFieldName)
    {
        EmitAttributes(sb, prop);
        sb.AppendLine($"    public {model.BuilderClassName} With{prop.Name}(global::System.Action<{dictBuilderType}> configure)");
        sb.AppendLine("    {");
        EmitBodyPrefix(sb, prop);

        if (builderFieldName is not null)
        {
            sb.AppendLine($"        {builderFieldName} = new {dictBuilderType}();");
            sb.AppendLine($"        configure({builderFieldName});");
        }
        else
        {
            sb.AppendLine($"        var __b = new {dictBuilderType}();");
            sb.AppendLine("        configure(__b);");
            sb.AppendLine($"        {prop.Name} = __b.Build();");
        }
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
    }

    private static void AppendDictBuilderSingular(StringBuilder sb, BuilderEmitModel model, BuilderPropertyModel prop,
        string dictBuilderType, string builderFieldName)
    {
        EmitAttributes(sb, prop);
        sb.AppendLine($"    public {model.BuilderClassName} With{prop.DictSingularName}({prop.DictKeyTypeFull} key, global::System.Action<{prop.DictValueBuilderClassName}> configure)");
        sb.AppendLine("    {");
        EmitBodyPrefix(sb, prop);
        sb.AppendLine($"        {builderFieldName} ??= new {dictBuilderType}();");
        sb.AppendLine($"        var __b = new {prop.DictValueBuilderClassName}();");
        sb.AppendLine("        configure(__b);");
        sb.AppendLine($"        {builderFieldName}.With(key, __b);");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
    }

    private static void AppendDictSimpleSingular(StringBuilder sb, BuilderEmitModel model, BuilderPropertyModel prop)
    {
        EmitAttributes(sb, prop);
        sb.AppendLine($"    public {model.BuilderClassName} With{prop.DictSingularName}({prop.DictKeyTypeFull} key, {prop.DictValueTypeFull} value)");
        sb.AppendLine("    {");
        EmitBodyPrefix(sb, prop);
        sb.AppendLine($"        {prop.Name} ??= new global::System.Collections.Generic.Dictionary<{prop.DictKeyTypeFull}, {prop.DictValueTypeFull}>();");
        sb.AppendLine($"        {prop.Name}[key] = value;");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
    }

    // ── List helpers ────────────────────────────────────────────────────────

    private static string? GetListBuilderFieldName(BuilderPropertyModel prop)
    {
        if (!prop.IsCollection || prop.ItemBuilderClassName is null)
            return null;
        return $"__{prop.Name}Builder";
    }

    private static string GetListBuilderType(BuilderPropertyModel prop)
    {
        const string ListBuilder = "global::FrenchExDev.Net.Builder.ListBuilder";
        var itemType = prop.ItemTypeFull!.TrimEnd('?');
        return $"{ListBuilder}<{itemType}, {prop.ItemBuilderClassName}>";
    }

    private static void AppendListSimpleOverload(StringBuilder sb, BuilderEmitModel model, BuilderPropertyModel prop)
    {
        EmitAttributes(sb, prop);
        sb.AppendLine($"    public {model.BuilderClassName} With{prop.CollectionSingularName}({prop.ItemTypeFull} value)");
        sb.AppendLine("    {");
        EmitBodyPrefix(sb, prop);
        sb.AppendLine($"        {prop.Name} ??= new global::System.Collections.Generic.List<{prop.ItemTypeFull}>();");
        sb.AppendLine($"        {prop.Name}.Add(value);");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
    }

    private static void AppendListBuilderOverloads(StringBuilder sb, BuilderEmitModel model, BuilderPropertyModel prop)
    {
        var builderFieldName = GetListBuilderFieldName(prop)!;
        var listBuilderType = GetListBuilderType(prop);
        var itemTypeNonNull = prop.ItemTypeFull!.TrimEnd('?');

        sb.AppendLine($"    private {listBuilderType}? {builderFieldName};");

        AppendListDirectOverload(sb, model, prop, builderFieldName, listBuilderType, itemTypeNonNull);
        AppendListBuilderActionOverload(sb, model, prop, builderFieldName, listBuilderType);
        AppendListBulkOverload(sb, model, prop, builderFieldName, listBuilderType);
    }

    private static void AppendListDirectOverload(StringBuilder sb, BuilderEmitModel model, BuilderPropertyModel prop,
        string builderFieldName, string listBuilderType, string itemTypeNonNull)
    {
        EmitAttributes(sb, prop);
        sb.AppendLine($"    public {model.BuilderClassName} With{prop.CollectionSingularName}({itemTypeNonNull} value)");
        sb.AppendLine("    {");
        EmitBodyPrefix(sb, prop);
        sb.AppendLine($"        {builderFieldName} ??= new {listBuilderType}();");
        sb.AppendLine($"        {builderFieldName}.Add(value);");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
    }

    private static void AppendListBuilderActionOverload(StringBuilder sb, BuilderEmitModel model, BuilderPropertyModel prop,
        string builderFieldName, string listBuilderType)
    {
        EmitAttributes(sb, prop);
        sb.AppendLine($"    public {model.BuilderClassName} With{prop.CollectionSingularName}(global::System.Action<{prop.ItemBuilderClassName}> configure)");
        sb.AppendLine("    {");
        EmitBodyPrefix(sb, prop);
        sb.AppendLine($"        {builderFieldName} ??= new {listBuilderType}();");
        sb.AppendLine($"        var __b = new {prop.ItemBuilderClassName}();");
        sb.AppendLine("        configure(__b);");
        sb.AppendLine($"        {builderFieldName}.Add(__b);");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
    }

    private static void AppendListBulkOverload(StringBuilder sb, BuilderEmitModel model, BuilderPropertyModel prop,
        string builderFieldName, string listBuilderType)
    {
        EmitAttributes(sb, prop);
        sb.AppendLine($"    public {model.BuilderClassName} With{prop.Name}(global::System.Action<{listBuilderType}> configure)");
        sb.AppendLine("    {");
        EmitBodyPrefix(sb, prop);
        sb.AppendLine($"        {builderFieldName} = new {listBuilderType}();");
        sb.AppendLine($"        configure({builderFieldName});");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
    }

    // ── Validation ──────────────────────────────────────────────────────────

    private static void AppendValidationMethods(StringBuilder sb, BuilderEmitModel model)
    {
        if (model.Properties.Count == 0) return;

        sb.AppendLine("    // ── Per-property validation (virtual, overridable) ────────────────");
        foreach (var prop in model.Properties)
        {
            sb.AppendLine(
                $"    protected virtual global::System.Collections.Generic.IEnumerable<global::System.Exception>?" +
                $" Validate{prop.Name}({prop.NullableTypeFull} value) => null;");

            if (prop.IsCollection && prop.ItemTypeFull is not null)
                sb.AppendLine(
                    $"    protected virtual global::System.Collections.Generic.IEnumerable<global::System.Exception>?" +
                    $" Validate{prop.Name}Item({prop.ItemTypeFull} item, int index) => null;");
        }
        sb.AppendLine();
    }

    private static void AppendValidateAsync(StringBuilder sb, BuilderEmitModel model)
    {
        const string ResultVR = "global::FrenchExDev.Net.Result.Result<global::FrenchExDev.Net.Builder.ValidationResult>";

        sb.AppendLine("    // ── ValidateAsync ─────────────────────────────────────────────────");
        sb.AppendLine($"    protected override global::System.Threading.Tasks.Task<{ResultVR}> ValidateAsync(");
        sb.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        var __result = new global::FrenchExDev.Net.Builder.ValidationResult();");
        sb.AppendLine($"        var __type = typeof({model.BuilderClassName});");

        if (model.Properties.Count > 0)
            sb.AppendLine();

        foreach (var prop in model.Properties)
            AppendPropertyValidation(sb, prop);

        if (model.ValidateAsyncEpilogue is not null)
        {
            sb.AppendLine();
            sb.AppendLine("        // ── Custom epilogue ──");
            sb.AppendLine(model.ValidateAsyncEpilogue);
            sb.AppendLine();
        }

        sb.AppendLine("        return global::System.Threading.Tasks.Task.FromResult(");
        sb.AppendLine("            global::FrenchExDev.Net.Result.Result<global::FrenchExDev.Net.Builder.ValidationResult>.Success(__result));");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendPropertyValidation(StringBuilder sb, BuilderPropertyModel prop)
    {
        const string EmptyErr = "global::System.Array.Empty<global::System.Exception>()";
        const string MemberName = "global::FrenchExDev.Net.Builder.MemberName";

        sb.AppendLine($"        foreach (var __err in Validate{prop.Name}({prop.Name}) ?? {EmptyErr})");
        sb.AppendLine($"            __result.AddError(new {MemberName}(nameof({prop.Name}), __type), __err);");

        if (prop.IsCollection && prop.ItemTypeFull is not null)
            AppendCollectionItemValidation(sb, prop);

        sb.AppendLine();
    }

    private static void AppendCollectionItemValidation(StringBuilder sb, BuilderPropertyModel prop)
    {
        const string EmptyErr = "global::System.Array.Empty<global::System.Exception>()";
        const string MemberName = "global::FrenchExDev.Net.Builder.MemberName";

        var idxVar = $"__{prop.Name}Idx";
        var itemVar = $"__{prop.Name}Item";
        sb.AppendLine($"        if ({prop.Name} is not null)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var {idxVar} = 0;");
        sb.AppendLine($"            foreach (var {itemVar} in {prop.Name})");
        sb.AppendLine("            {");
        sb.AppendLine($"                foreach (var __err in Validate{prop.Name}Item({itemVar}, {idxVar}) ?? {EmptyErr})");
        sb.AppendLine($"                    __result.AddError(new {MemberName}(" +
            "$\"" + $"{{nameof({prop.Name})}}[{{{idxVar}}}]" + "\", __type), __err);");
        sb.AppendLine($"                {idxVar}++;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static void AppendBuildException(StringBuilder sb, BuilderEmitModel model)
    {
        const string ResultVR = "global::FrenchExDev.Net.Result.Result<global::FrenchExDev.Net.Builder.ValidationResult>";

        sb.AppendLine("    // ── BuildException ───────────────────────────────────────────────");

        if (model.ExceptionFullName is not null)
        {
            sb.AppendLine($"    protected override {model.ExceptionFullName} TypedBuildException(");
            sb.AppendLine($"        {ResultVR} validationResult)");
            sb.AppendLine("        => new(validationResult.ValueOrThrow().ToDataAnnotationsValidationResult().ErrorMessage);");
        }
        else
        {
            sb.AppendLine("    protected override global::System.Exception BuildException(");
            sb.AppendLine($"        {ResultVR} validationResult)");
            sb.AppendLine("        => new global::System.InvalidOperationException(");
            sb.AppendLine("            validationResult.ValueOrThrow().ToDataAnnotationsValidationResult().ErrorMessage);");
        }

        sb.AppendLine();
    }

    // ── Instantiate & CreateInstance ─────────────────────────────────────────

    private static void AppendInstantiate(StringBuilder sb, BuilderEmitModel model, string classRef)
    {
        var refT = $"global::FrenchExDev.Net.Builder.Reference<{classRef}>";
        var resultRefT = $"global::FrenchExDev.Net.Result.Result<{refT}>";

        sb.AppendLine("    // ── Instantiate (sealed bridge) ───────────────────────────────────");
        sb.AppendLine($"    protected sealed override async global::System.Threading.Tasks.Task<{resultRefT}> Instantiate(");
        sb.AppendLine($"        {refT} reference,");
        sb.AppendLine("        global::FrenchExDev.Net.Builder.VisitedObjects visitedObjects,");
        sb.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");

        AppendDeferredBuilds(sb, model);

        sb.AppendLine($"        var __value = CreateInstance();");
        sb.AppendLine("        reference.Resolve(__value);");
        sb.AppendLine($"        return {resultRefT}.Success(reference);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendDeferredBuilds(StringBuilder sb, BuilderEmitModel model)
    {
        foreach (var prop in model.Properties)
        {
            var dictField = GetDictBuilderFieldName(prop);
            if (dictField is not null)
            {
                var nullableSuffix = prop.DictValueTypeFull!.EndsWith("?") ? "!" : "";
                sb.AppendLine($"        if ({dictField} is not null)");
                sb.AppendLine($"            {prop.Name} = (await {dictField}.BuildAsync(visitedObjects, cancellationToken)){nullableSuffix};");
            }

            var listField = GetListBuilderFieldName(prop);
            if (listField is not null)
            {
                sb.AppendLine($"        if ({listField} is not null)");
                sb.AppendLine($"            {prop.Name} = await {listField}.BuildAsync(visitedObjects, cancellationToken);");
            }
        }
    }

    private static void AppendCreateInstance(StringBuilder sb, BuilderEmitModel model, string classRef)
    {
        sb.AppendLine("    // ── CreateInstance (strategy-driven) ───────────────────────────────");

        if (model.Instantiation == "custom")
            sb.AppendLine($"    protected abstract {classRef} CreateInstance();");
        else if (model.Instantiation == "ctor")
            AppendCreateInstancePositional(sb, model, classRef, $"new {classRef}");
        else if (model.Instantiation.StartsWith("factory:"))
            AppendCreateInstancePositional(sb, model, classRef, $"{classRef}.{model.Instantiation.Substring("factory:".Length)}");
        else
            AppendCreateInstanceInit(sb, model, classRef);
    }

    private static void AppendCreateInstancePositional(StringBuilder sb, BuilderEmitModel model, string classRef, string callTarget)
    {
        sb.AppendLine($"    protected virtual {classRef} CreateInstance()");
        sb.AppendLine("    {");
        sb.Append($"        return {callTarget}(");
        for (int i = 0; i < model.Properties.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(model.Properties[i].InstantiationExpression ?? model.Properties[i].Name);
        }
        sb.AppendLine(");");
        sb.AppendLine("    }");
    }

    private static void AppendCreateInstanceInit(StringBuilder sb, BuilderEmitModel model, string classRef)
    {
        sb.AppendLine($"    protected virtual {classRef} CreateInstance()");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {classRef}");
        sb.AppendLine("        {");
        foreach (var prop in model.Properties)
        {
            var expr = prop.InstantiationExpression ?? prop.Name;
            sb.AppendLine($"            {prop.Name} = {expr},");
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }
}
