using System.Text;

namespace FrenchExDev.Net.Builder.SourceGenerator.Lib;

/// <summary>
/// Emits a full builder class from a <see cref="BuilderEmitModel"/>.
/// No Roslyn dependency — usable by any source generator targeting netstandard2.0.
/// </summary>
public static class BuilderEmitter
{
    public static string Emit(BuilderEmitModel model)
    {
        var sb = new StringBuilder(4096);

        var classRef = string.IsNullOrEmpty(model.Namespace)
            ? $"global::{model.TargetClassName}"
            : $"global::{model.Namespace}.{model.TargetClassName}";

        var baseClass = model.ExceptionFullName is not null
            ? $"global::FrenchExDev.Net.Builder.AbstractBuilder<{classRef}, {model.ExceptionFullName}>"
            : $"global::FrenchExDev.Net.Builder.AbstractBuilder<{classRef}>";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0618 // Obsolete members");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        var classModifier = model.Instantiation == "custom" ? "abstract " : "";
        sb.AppendLine($"public {classModifier}partial class {model.BuilderClassName} : {baseClass}");
        sb.AppendLine("{");

        // Preamble (custom fields, constructors, etc.)
        if (model.Preamble is not null)
        {
            sb.AppendLine(model.Preamble);
            sb.AppendLine();
        }

        AppendInputProperties(sb, model);
        AppendValidationMethods(sb, model);
        AppendValidateAsync(sb, model);
        AppendBuildException(sb, model);
        AppendInstantiate(sb, model, classRef);
        AppendCreateInstance(sb, model, classRef);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendInputProperties(StringBuilder sb, BuilderEmitModel model)
    {
        sb.AppendLine("    // ── Input properties ─────────────────────────────────────────────");
        foreach (var prop in model.Properties)
        {
            sb.AppendLine($"    protected {prop.NullableTypeFull} {prop.Name} {{ get; private set; }}");

            // With method attributes
            if (prop.WithMethodAttributes is not null)
            {
                foreach (var attr in prop.WithMethodAttributes)
                    sb.AppendLine($"    {attr}");
            }

            // With method — inline or multi-line depending on body prefix
            if (prop.WithMethodBodyPrefix is not null)
            {
                sb.AppendLine($"    public {model.BuilderClassName} With{prop.Name}({prop.NullableTypeFull} value)");
                sb.AppendLine("    {");
                sb.AppendLine($"        {prop.WithMethodBodyPrefix}");
                sb.AppendLine($"        {prop.Name} = value;");
                sb.AppendLine("        return this;");
                sb.AppendLine("    }");
            }
            else
            {
                sb.AppendLine($"    public {model.BuilderClassName} With{prop.Name}({prop.NullableTypeFull} value) {{ {prop.Name} = value; return this; }}");
            }

            // Dictionary lambda overload
            if (prop.IsDictionary && prop.DictKeyTypeFull is not null && prop.DictValueTypeFull is not null)
            {
                AppendDictionaryOverloads(sb, model, prop);
            }
        }
        sb.AppendLine();
    }

    private static string? GetDictBuilderFieldName(BuilderPropertyModel prop)
    {
        if (!prop.IsDictionary || prop.DictValueBuilderClassName is null)
            return null;
        return $"__{prop.Name}Builder";
    }

    private static string GetDictBuilderType(BuilderPropertyModel prop)
    {
        const string DictBuilder = "global::FrenchExDev.Net.Builder.DictionaryBuilder";
        // Strip nullable ? from value type for the 3-param DictionaryBuilder (notnull constraint)
        var valueType = prop.DictValueTypeFull!.TrimEnd('?');
        return $"{DictBuilder}<{prop.DictKeyTypeFull}, {valueType}, {prop.DictValueBuilderClassName}>";
    }

    private static void AppendDictionaryOverloads(StringBuilder sb, BuilderEmitModel model, BuilderPropertyModel prop)
    {
        const string DictBuilder = "global::FrenchExDev.Net.Builder.DictionaryBuilder";

        var hasValueBuilder = prop.DictValueBuilderClassName is not null;
        var builderFieldName = GetDictBuilderFieldName(prop);

        // For 3-param DictionaryBuilder: strip nullable from value type (notnull constraint)
        var dictBuilderType = hasValueBuilder
            ? GetDictBuilderType(prop)
            : $"{DictBuilder}<{prop.DictKeyTypeFull}, {prop.DictValueTypeFull}>";

        // Private builder field (only for 3-param, deferred build)
        if (builderFieldName is not null)
            sb.AppendLine($"    private {dictBuilderType}? {builderFieldName};");

        // Emit same version attributes as the value overload
        if (prop.WithMethodAttributes is not null)
        {
            foreach (var attr in prop.WithMethodAttributes)
                sb.AppendLine($"    {attr}");
        }

        // Bulk lambda overload: WithServices(Action<DictionaryBuilder<...>> configure)
        sb.AppendLine($"    public {model.BuilderClassName} With{prop.Name}(global::System.Action<{dictBuilderType}> configure)");
        sb.AppendLine("    {");
        if (prop.WithMethodBodyPrefix is not null)
            sb.AppendLine($"        {prop.WithMethodBodyPrefix}");

        if (builderFieldName is not null)
        {
            // Deferred: store the builder, build during Instantiate
            sb.AppendLine($"        {builderFieldName} = new {dictBuilderType}();");
            sb.AppendLine($"        configure({builderFieldName});");
        }
        else
        {
            // No value builder: build immediately (2-param, sync)
            sb.AppendLine($"        var __b = new {dictBuilderType}();");
            sb.AppendLine("        configure(__b);");
            sb.AppendLine($"        {prop.Name} = __b.Build();");
        }
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");

        // Single-entry convenience: WithService(key, Action<TValueBuilder> configure)
        if (prop.DictSingularName is not null && builderFieldName is not null)
        {
            if (prop.WithMethodAttributes is not null)
            {
                foreach (var attr in prop.WithMethodAttributes)
                    sb.AppendLine($"    {attr}");
            }

            sb.AppendLine($"    public {model.BuilderClassName} With{prop.DictSingularName}({prop.DictKeyTypeFull} key, global::System.Action<{prop.DictValueBuilderClassName}> configure)");
            sb.AppendLine("    {");
            if (prop.WithMethodBodyPrefix is not null)
                sb.AppendLine($"        {prop.WithMethodBodyPrefix}");
            sb.AppendLine($"        {builderFieldName} ??= new {dictBuilderType}();");
            sb.AppendLine($"        var __b = new {prop.DictValueBuilderClassName}();");
            sb.AppendLine("        configure(__b);");
            sb.AppendLine($"        {builderFieldName}.With(key, __b);");
            sb.AppendLine("        return this;");
            sb.AppendLine("    }");
        }
    }

    private static void AppendValidationMethods(StringBuilder sb, BuilderEmitModel model)
    {
        if (model.Properties.Count == 0) return;

        sb.AppendLine("    // ── Per-property validation (virtual, overridable) ────────────────");
        foreach (var prop in model.Properties)
        {
            sb.AppendLine(
                $"    protected virtual global::System.Collections.Generic.IEnumerable<global::System.Exception>?" +
                $" Validate{prop.Name}({prop.NullableTypeFull} value) => null;");

            if (prop.IsCollection && prop.ItemTypeFull is not null)
                sb.AppendLine(
                    $"    protected virtual global::System.Collections.Generic.IEnumerable<global::System.Exception>?" +
                    $" Validate{prop.Name}Item({prop.ItemTypeFull} item, int index) => null;");
        }
        sb.AppendLine();
    }

    private static void AppendValidateAsync(StringBuilder sb, BuilderEmitModel model)
    {
        const string VR = "global::FrenchExDev.Net.Builder.ValidationResult";
        const string ResultVR = "global::FrenchExDev.Net.Result.Result<global::FrenchExDev.Net.Builder.ValidationResult>";
        const string EmptyErr = "global::System.Array.Empty<global::System.Exception>()";
        const string MemberName = "global::FrenchExDev.Net.Builder.MemberName";

        sb.AppendLine("    // ── ValidateAsync ─────────────────────────────────────────────────");
        sb.AppendLine($"    protected override global::System.Threading.Tasks.Task<{ResultVR}> ValidateAsync(");
        sb.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var __result = new {VR}();");
        sb.AppendLine($"        var __type = typeof({model.BuilderClassName});");

        if (model.Properties.Count > 0)
            sb.AppendLine();

        foreach (var prop in model.Properties)
        {
            sb.AppendLine(
                $"        foreach (var __err in Validate{prop.Name}({prop.Name}) ?? {EmptyErr})");
            sb.AppendLine(
                $"            __result.AddError(new {MemberName}(nameof({prop.Name}), __type), __err);");

            if (prop.IsCollection && prop.ItemTypeFull is not null)
            {
                var idxVar = $"__{prop.Name}Idx";
                var itemVar = $"__{prop.Name}Item";
                sb.AppendLine($"        if ({prop.Name} is not null)");
                sb.AppendLine("        {");
                sb.AppendLine($"            var {idxVar} = 0;");
                sb.AppendLine($"            foreach (var {itemVar} in {prop.Name})");
                sb.AppendLine("            {");
                sb.AppendLine(
                    $"                foreach (var __err in Validate{prop.Name}Item({itemVar}, {idxVar}) ?? {EmptyErr})");
                sb.AppendLine(
                    $"                    __result.AddError(new {MemberName}(" +
                    "$\"" + $"{{nameof({prop.Name})}}[{{{idxVar}}}]" + "\", __type), __err);");
                sb.AppendLine($"                {idxVar}++;");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
            }

            sb.AppendLine();
        }

        sb.AppendLine(
            $"        return global::System.Threading.Tasks.Task.FromResult(");
        sb.AppendLine(
            $"            global::FrenchExDev.Net.Result.Result<{VR}>.Success(__result));");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendBuildException(StringBuilder sb, BuilderEmitModel model)
    {
        const string ResultVR = "global::FrenchExDev.Net.Result.Result<global::FrenchExDev.Net.Builder.ValidationResult>";

        sb.AppendLine("    // ── BuildException ───────────────────────────────────────────────");

        if (model.ExceptionFullName is not null)
        {
            sb.AppendLine($"    protected override {model.ExceptionFullName} TypedBuildException(");
            sb.AppendLine($"        {ResultVR} validationResult)");
            sb.AppendLine("        => new(validationResult.ValueOrThrow().ToDataAnnotationsValidationResult().ErrorMessage);");
        }
        else
        {
            sb.AppendLine("    protected override global::System.Exception BuildException(");
            sb.AppendLine($"        {ResultVR} validationResult)");
            sb.AppendLine("        => new global::System.InvalidOperationException(");
            sb.AppendLine("            validationResult.ValueOrThrow().ToDataAnnotationsValidationResult().ErrorMessage);");
        }

        sb.AppendLine();
    }

    private static void AppendInstantiate(StringBuilder sb, BuilderEmitModel model, string classRef)
    {
        var refT = $"global::FrenchExDev.Net.Builder.Reference<{classRef}>";
        var resultRefT = $"global::FrenchExDev.Net.Result.Result<{refT}>";

        sb.AppendLine("    // ── Instantiate (sealed bridge) ───────────────────────────────────");
        sb.AppendLine($"    protected sealed override async global::System.Threading.Tasks.Task<{resultRefT}> Instantiate(");
        sb.AppendLine($"        {refT} reference,");
        sb.AppendLine("        global::FrenchExDev.Net.Builder.VisitedObjects visitedObjects,");
        sb.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");

        // Build dictionary properties from stored builders (deferred)
        foreach (var prop in model.Properties)
        {
            var fieldName = GetDictBuilderFieldName(prop);
            if (fieldName is null) continue;

            var valueTypeIsNullable = prop.DictValueTypeFull!.EndsWith("?");
            // NRT: Dictionary<K, V> and Dictionary<K, V?> are same at runtime; use ! to suppress warning
            var nullableSuffix = valueTypeIsNullable ? "!" : "";

            sb.AppendLine($"        if ({fieldName} is not null)");
            sb.AppendLine($"            {prop.Name} = (await {fieldName}.BuildAsync(visitedObjects, cancellationToken)){nullableSuffix};");
        }

        sb.AppendLine($"        var __value = CreateInstance();");
        sb.AppendLine("        reference.Resolve(__value);");
        sb.AppendLine($"        return {resultRefT}.Success(reference);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendCreateInstance(StringBuilder sb, BuilderEmitModel model, string classRef)
    {
        sb.AppendLine("    // ── CreateInstance (strategy-driven) ───────────────────────────────");

        if (model.Instantiation == "custom")
        {
            sb.AppendLine($"    protected abstract {classRef} CreateInstance();");
        }
        else if (model.Instantiation == "ctor")
        {
            sb.AppendLine($"    protected virtual {classRef} CreateInstance()");
            sb.AppendLine("    {");
            sb.Append($"        return new {classRef}(");
            for (int i = 0; i < model.Properties.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                var prop = model.Properties[i];
                sb.Append(prop.InstantiationExpression ?? prop.Name);
            }
            sb.AppendLine(");");
            sb.AppendLine("    }");
        }
        else if (model.Instantiation.StartsWith("factory:"))
        {
            var methodName = model.Instantiation.Substring("factory:".Length);
            sb.AppendLine($"    protected virtual {classRef} CreateInstance()");
            sb.AppendLine("    {");
            sb.Append($"        return {classRef}.{methodName}(");
            for (int i = 0; i < model.Properties.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                var prop = model.Properties[i];
                sb.Append(prop.InstantiationExpression ?? prop.Name);
            }
            sb.AppendLine(");");
            sb.AppendLine("    }");
        }
        else
        {
            // "init" (default) — object initializer
            sb.AppendLine($"    protected virtual {classRef} CreateInstance()");
            sb.AppendLine("    {");
            sb.AppendLine($"        return new {classRef}");
            sb.AppendLine("        {");
            foreach (var prop in model.Properties)
            {
                var expr = prop.InstantiationExpression ?? prop.Name;
                sb.AppendLine($"            {prop.Name} = {expr},");
            }
            sb.AppendLine("        };");
            sb.AppendLine("    }");
        }
    }
}
