using System.CommandLine;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using FrenchExDev.Net.Vos;
using FrenchExDev.Net.Vos.Cli.Commands;
using FrenchExDev.Net.Vos.Cli.Exceptions;
using FrenchExDev.Net.Vos.Abstractions;
using FrenchExDev.Net.Vos.Abstractions.IO;
using FrenchExDev.Net.Vos.Lib.Abstractions;
using FrenchExDev.Net.Vos.VosFile;
using FrenchExDev.Net.Vos.Infra.FileSystem;
using FrenchExDev.Net.Vos.Infra.Vagrant;

// ── DI Container ────────────────────────────────────────────────────
var services = new ServiceCollection();

// Logging
services.AddLogging(b => b.AddConsole().SetMinimumLevel(LogLevel.Information));

// IO + VosFile (not covered by Injectable SG — no [Injectable] on these)
services.AddSingleton<IFileSystem, PhysicalFileSystem>();
services.AddSingleton<IVosFileReader, VosFileReader>();
services.AddSingleton<IVosFileWriter, VosFileWriter>();

// Backend (not in Lib assembly — separate registration)
services.AddSingleton<IVosBackend, VagrantBackend>();

// Lib services + VosEventEmitter (auto-generated by Injectable SG)
services.AddFrenchExDevNetVosLibInjectables();

// CLI commands
services.AddTransient<UpCommand>();
services.AddTransient<HaltCommand>();
services.AddTransient<StatusCommand>();
services.AddTransient<InitCommand>();
services.AddTransient<VersionCommand>();

var provider = services.BuildServiceProvider();

// ── Event subscriptions ─────────────────────────────────────────────
var emitter = provider.GetRequiredService<IVosEventEmitter>();
emitter.Subscribe<VmOperationFailed>(e => Console.Error.WriteLine($"ERROR [{e.InstanceName}]: {e.Error}"));

// ── Command tree ────────────────────────────────────────────────────
var root = new RootCommand("vos - Vagrant On Steroids");

root.Subcommands.Add(provider.GetRequiredService<UpCommand>());
root.Subcommands.Add(provider.GetRequiredService<HaltCommand>());
root.Subcommands.Add(provider.GetRequiredService<StatusCommand>());
root.Subcommands.Add(provider.GetRequiredService<InitCommand>());
root.Subcommands.Add(provider.GetRequiredService<VersionCommand>());

// ── Run ─────────────────────────────────────────────────────────────
try
{
    var parseResult = root.Parse(args);
    return await parseResult.InvokeAsync();
}
catch (VosCliException ex)
{
    Console.Error.WriteLine($"Error: {ex.Message}");
    return 1;
}
