using FrenchExDev.Net.Entity.Dsl.SourceGenerator.Lib;
using Xunit;

namespace FrenchExDev.Net.Entity.Dsl.Tests;

public class EntityConfigurationEmitterTests
{
    private static EntityEmitModel CreateModel(string className = "Order", string ns = "MyApp.Domain") => new()
    {
        Namespace = ns,
        ClassName = className,
        ClassFullName = $"global::{ns}.{className}"
    };

    [Fact]
    public void EmitBase_contains_auto_generated_header()
    {
        var code = EntityConfigurationEmitter.EmitBase(CreateModel());
        Assert.StartsWith("// <auto-generated/>", code);
        Assert.Contains("#nullable enable", code);
    }

    [Fact]
    public void EmitBase_class_is_abstract()
    {
        var code = EntityConfigurationEmitter.EmitBase(CreateModel());
        Assert.Contains("public abstract class OrderConfigurationBase", code);
    }

    [Fact]
    public void EmitBase_has_pre_and_post_configure_hooks()
    {
        var code = EntityConfigurationEmitter.EmitBase(CreateModel());
        Assert.Contains("protected virtual void PreConfigure(", code);
        Assert.Contains("protected virtual void PostConfigure(", code);
    }

    [Fact]
    public void EmitBase_emits_table_mapping()
    {
        var model = CreateModel();
        model.TableName = "Orders";
        model.Schema = "sales";
        var code = EntityConfigurationEmitter.EmitBase(model);
        Assert.Contains("builder.ToTable(\"Orders\", \"sales\")", code);
    }

    [Fact]
    public void EmitBase_emits_table_without_schema()
    {
        var model = CreateModel();
        model.TableName = "Orders";
        var code = EntityConfigurationEmitter.EmitBase(model);
        Assert.Contains("builder.ToTable(\"Orders\")", code);
        Assert.DoesNotContain("sales", code);
    }

    [Fact]
    public void EmitBase_emits_single_primary_key()
    {
        var model = CreateModel();
        model.PrimaryKeyProperties.Add(new KeyPropertyModel
        {
            PropertyName = "Id", ValueGenerated = "OnAdd"
        });
        var code = EntityConfigurationEmitter.EmitBase(model);
        Assert.Contains("builder.HasKey(e => e.Id)", code);
        Assert.Contains("ValueGeneratedOnAdd()", code);
    }

    [Fact]
    public void EmitBase_emits_composite_primary_key_ordered()
    {
        var model = CreateModel();
        model.PrimaryKeyProperties.Add(new KeyPropertyModel { PropertyName = "CourseId", Order = 1 });
        model.PrimaryKeyProperties.Add(new KeyPropertyModel { PropertyName = "StudentId", Order = 0 });
        var code = EntityConfigurationEmitter.EmitBase(model);
        Assert.Contains("builder.HasKey(e => new { e.StudentId, e.CourseId })", code);
    }

    [Fact]
    public void EmitBase_emits_value_generated_never()
    {
        var model = CreateModel();
        model.PrimaryKeyProperties.Add(new KeyPropertyModel
        {
            PropertyName = "Id", ValueGenerated = "None"
        });
        var code = EntityConfigurationEmitter.EmitBase(model);
        Assert.Contains("ValueGeneratedNever()", code);
    }

    [Fact]
    public void EmitBase_has_one_configure_method_per_property()
    {
        var model = CreateModel();
        model.Properties.Add(new PropertyConfigModel { PropertyName = "OrderNumber" });
        model.Properties.Add(new PropertyConfigModel { PropertyName = "Total" });
        var code = EntityConfigurationEmitter.EmitBase(model);
        Assert.Contains("protected virtual void ConfigureOrderNumber(", code);
        Assert.Contains("protected virtual void ConfigureTotal(", code);
    }

    [Fact]
    public void EmitBase_emits_property_is_required()
    {
        var model = CreateModel();
        model.Properties.Add(new PropertyConfigModel
        {
            PropertyName = "Name", IsRequired = true
        });
        var code = EntityConfigurationEmitter.EmitBase(model);
        Assert.Contains(".IsRequired()", code);
    }

    [Fact]
    public void EmitBase_emits_property_max_length()
    {
        var model = CreateModel();
        model.Properties.Add(new PropertyConfigModel
        {
            PropertyName = "Name", MaxLength = 100
        });
        var code = EntityConfigurationEmitter.EmitBase(model);
        Assert.Contains(".HasMaxLength(100)", code);
    }

    [Fact]
    public void EmitBase_emits_column_name()
    {
        var model = CreateModel();
        model.Properties.Add(new PropertyConfigModel
        {
            PropertyName = "OrderNumber", ColumnName = "order_number"
        });
        var code = EntityConfigurationEmitter.EmitBase(model);
        Assert.Contains(".HasColumnName(\"order_number\")", code);
    }

    [Fact]
    public void EmitBase_emits_column_type()
    {
        var model = CreateModel();
        model.Properties.Add(new PropertyConfigModel
        {
            PropertyName = "Data", ColumnType = "jsonb"
        });
        var code = EntityConfigurationEmitter.EmitBase(model);
        Assert.Contains(".HasColumnType(\"jsonb\")", code);
    }

    [Fact]
    public void EmitBase_skips_not_mapped_properties()
    {
        var model = CreateModel();
        model.Properties.Add(new PropertyConfigModel
        {
            PropertyName = "Computed", IsNotMapped = true
        });
        var code = EntityConfigurationEmitter.EmitBase(model);
        Assert.DoesNotContain("ConfigureComputed", code);
    }

    [Fact]
    public void EmitBase_orchestrator_calls_all_virtuals_in_order()
    {
        var model = CreateModel();
        model.TableName = "Orders";
        model.PrimaryKeyProperties.Add(new KeyPropertyModel { PropertyName = "Id" });
        model.Properties.Add(new PropertyConfigModel { PropertyName = "Name" });
        var code = EntityConfigurationEmitter.EmitBase(model);

        var preIdx = code.IndexOf("PreConfigure(builder)");
        var tableIdx = code.IndexOf("ConfigureTable(builder)");
        var pkIdx = code.IndexOf("ConfigurePrimaryKey(builder)");
        var nameIdx = code.IndexOf("ConfigureName(builder)");
        var postIdx = code.IndexOf("PostConfigure(builder)");

        // In the orchestrator (not the declarations)
        Assert.True(preIdx < tableIdx);
        Assert.True(tableIdx < pkIdx);
        Assert.True(pkIdx < nameIdx);
        Assert.True(nameIdx < postIdx);
    }

    [Fact]
    public void EmitPartialStub_extends_base()
    {
        var code = EntityConfigurationEmitter.EmitPartialStub(CreateModel());
        Assert.Contains("public partial class OrderConfiguration : OrderConfigurationBase", code);
    }

    [Fact]
    public void EmitPartialStub_is_empty()
    {
        var code = EntityConfigurationEmitter.EmitPartialStub(CreateModel());
        // Should contain the class but no methods
        Assert.Contains("public partial class OrderConfiguration", code);
        Assert.DoesNotContain("protected", code);
    }

    [Fact]
    public void EmitRegistration_implements_ientitytypeconfiguration()
    {
        var code = EntityConfigurationEmitter.EmitRegistration(CreateModel());
        Assert.Contains("IEntityTypeConfiguration<global::MyApp.Domain.Order>", code);
    }

    [Fact]
    public void EmitRegistration_delegates_to_configuration_class()
    {
        var code = EntityConfigurationEmitter.EmitRegistration(CreateModel());
        Assert.Contains("new OrderConfiguration().Configure(builder)", code);
    }
}
