using FrenchExDev.Net.Injectable.SourceGenerator.Lib;
using Xunit;

namespace FrenchExDev.Net.Injectable.SourceGenerator.Lib.Tests;

public class EmitSimpleInjectorTests
{
    [Fact]
    public void Generates_singleton_with_interface()
    {
        var model = new InjectableEmitModel("TestApp", new[]
        {
            new InjectableServiceModel("global::TestApp.Foo", new[] { "global::TestApp.IFoo" }, "Singleton")
        });

        var code = InjectableEmitter.EmitSimpleInjector(model);

        Assert.Contains("container.Register<global::TestApp.IFoo, global::TestApp.Foo>(global::SimpleInjector.Lifestyle.Singleton)", code);
        Assert.Contains("AddTestAppInjectables", code);
        Assert.Contains("namespace SimpleInjector;", code);
    }

    [Fact]
    public void Generates_scoped_with_interface()
    {
        var model = new InjectableEmitModel("TestApp", new[]
        {
            new InjectableServiceModel("global::TestApp.Bar", new[] { "global::TestApp.IBar" }, "Scoped")
        });

        var code = InjectableEmitter.EmitSimpleInjector(model);

        Assert.Contains("container.Register<global::TestApp.IBar, global::TestApp.Bar>(global::SimpleInjector.Lifestyle.Scoped)", code);
    }

    [Fact]
    public void Generates_transient_self_registration()
    {
        var model = new InjectableEmitModel("TestApp", new[]
        {
            new InjectableServiceModel("global::TestApp.Baz", new string[0], "Transient")
        });

        var code = InjectableEmitter.EmitSimpleInjector(model);

        Assert.Contains("container.Register<global::TestApp.Baz>(global::SimpleInjector.Lifestyle.Transient)", code);
    }

    [Fact]
    public void Generates_multiple_interfaces()
    {
        var model = new InjectableEmitModel("TestApp", new[]
        {
            new InjectableServiceModel("global::TestApp.Multi", new[] { "global::TestApp.IA", "global::TestApp.IB" }, "Singleton")
        });

        var code = InjectableEmitter.EmitSimpleInjector(model);

        Assert.Contains("container.Register<global::TestApp.IA, global::TestApp.Multi>(global::SimpleInjector.Lifestyle.Singleton)", code);
        Assert.Contains("container.Register<global::TestApp.IB, global::TestApp.Multi>(global::SimpleInjector.Lifestyle.Singleton)", code);
    }

    [Fact]
    public void Contains_auto_generated_header()
    {
        var model = new InjectableEmitModel("X", new[]
        {
            new InjectableServiceModel("global::X.S", new string[0], "Transient")
        });

        var code = InjectableEmitter.EmitSimpleInjector(model);

        Assert.StartsWith("// <auto-generated />", code);
        Assert.Contains("#nullable enable", code);
    }

    [Fact]
    public void Returns_container()
    {
        var model = new InjectableEmitModel("X", new[]
        {
            new InjectableServiceModel("global::X.S", new string[0], "Transient")
        });

        var code = InjectableEmitter.EmitSimpleInjector(model);

        Assert.Contains("return container;", code);
    }

    [Fact]
    public void Generates_decorator()
    {
        var model = new InjectableEmitModel("TestApp", new InjectableServiceModel[0],
            new[] { new InjectableDecoratorModel("global::TestApp.FooDecorator", "global::TestApp.IFoo", 0) });

        var code = InjectableEmitter.EmitSimpleInjector(model);

        Assert.Contains("container.RegisterDecorator<global::TestApp.IFoo, global::TestApp.FooDecorator>()", code);
    }

    [Fact]
    public void Multiple_services_all_emitted()
    {
        var model = new InjectableEmitModel("App", new[]
        {
            new InjectableServiceModel("global::App.A", new[] { "global::App.IA" }, "Singleton"),
            new InjectableServiceModel("global::App.B", new string[0], "Transient"),
            new InjectableServiceModel("global::App.C", new[] { "global::App.IC" }, "Scoped")
        });

        var code = InjectableEmitter.EmitSimpleInjector(model);

        Assert.Contains("Register<global::App.IA, global::App.A>", code);
        Assert.Contains("Register<global::App.B>", code);
        Assert.Contains("Register<global::App.IC, global::App.C>", code);
    }
}
