using FrenchExDev.Net.Injectable.SourceGenerator.Lib;
using Xunit;

namespace FrenchExDev.Net.Injectable.SourceGenerator.Lib.Tests;

public class EmitMicrosoftTests
{
    // ── v1 tests (backward compatibility) ───────────────────────────

    [Fact]
    public void Generates_singleton_with_interface()
    {
        var model = new InjectableEmitModel("TestApp", new[]
        {
            new InjectableServiceModel("global::TestApp.Foo", new[] { "global::TestApp.IFoo" }, "Singleton")
        });

        var code = InjectableEmitter.EmitMicrosoft(model);

        Assert.Contains("services.AddSingleton<global::TestApp.IFoo, global::TestApp.Foo>()", code);
        Assert.Contains("AddTestAppInjectables", code);
        Assert.Contains("namespace Microsoft.Extensions.DependencyInjection;", code);
    }

    [Fact]
    public void Generates_scoped_with_interface()
    {
        var model = new InjectableEmitModel("TestApp", new[]
        {
            new InjectableServiceModel("global::TestApp.Bar", new[] { "global::TestApp.IBar" }, "Scoped")
        });

        var code = InjectableEmitter.EmitMicrosoft(model);

        Assert.Contains("services.AddScoped<global::TestApp.IBar, global::TestApp.Bar>()", code);
    }

    [Fact]
    public void Generates_transient_self_registration()
    {
        var model = new InjectableEmitModel("TestApp", new[]
        {
            new InjectableServiceModel("global::TestApp.Baz", new string[0], "Transient")
        });

        var code = InjectableEmitter.EmitMicrosoft(model);

        Assert.Contains("services.AddTransient<global::TestApp.Baz>()", code);
    }

    [Fact]
    public void Generates_multiple_interfaces()
    {
        var model = new InjectableEmitModel("TestApp", new[]
        {
            new InjectableServiceModel("global::TestApp.Multi", new[] { "global::TestApp.IA", "global::TestApp.IB" }, "Singleton")
        });

        var code = InjectableEmitter.EmitMicrosoft(model);

        Assert.Contains("services.AddSingleton<global::TestApp.IA, global::TestApp.Multi>()", code);
        Assert.Contains("services.AddSingleton<global::TestApp.IB, global::TestApp.Multi>()", code);
    }

    [Fact]
    public void Contains_auto_generated_header()
    {
        var model = new InjectableEmitModel("X", new[]
        {
            new InjectableServiceModel("global::X.S", new string[0], "Transient")
        });

        var code = InjectableEmitter.EmitMicrosoft(model);

        Assert.StartsWith("// <auto-generated />", code);
        Assert.Contains("#nullable enable", code);
    }

    [Fact]
    public void Returns_IServiceCollection()
    {
        var model = new InjectableEmitModel("X", new[]
        {
            new InjectableServiceModel("global::X.S", new string[0], "Transient")
        });

        var code = InjectableEmitter.EmitMicrosoft(model);

        Assert.Contains("return services;", code);
    }

    [Fact]
    public void Multiple_services_all_emitted()
    {
        var model = new InjectableEmitModel("App", new[]
        {
            new InjectableServiceModel("global::App.A", new[] { "global::App.IA" }, "Singleton"),
            new InjectableServiceModel("global::App.B", new string[0], "Transient"),
            new InjectableServiceModel("global::App.C", new[] { "global::App.IC" }, "Scoped")
        });

        var code = InjectableEmitter.EmitMicrosoft(model);

        Assert.Contains("AddSingleton<global::App.IA, global::App.A>", code);
        Assert.Contains("AddTransient<global::App.B>", code);
        Assert.Contains("AddScoped<global::App.IC, global::App.C>", code);
    }

    // ── v2: TryAdd ──────────────────────────────────────────────────

    [Fact]
    public void TryAdd_generates_TryAddSingleton()
    {
        var model = new InjectableEmitModel("App", new[]
        {
            new InjectableServiceModel("global::App.Foo", new[] { "global::App.IFoo" }, "Singleton", tryAdd: true)
        });

        var code = InjectableEmitter.EmitMicrosoft(model);

        Assert.Contains("services.TryAddSingleton<global::App.IFoo, global::App.Foo>()", code);
        Assert.DoesNotContain("services.AddSingleton", code);
    }

    [Fact]
    public void TryAdd_generates_TryAddTransient_self()
    {
        var model = new InjectableEmitModel("App", new[]
        {
            new InjectableServiceModel("global::App.Baz", new string[0], "Transient", tryAdd: true)
        });

        var code = InjectableEmitter.EmitMicrosoft(model);

        Assert.Contains("services.TryAddTransient<global::App.Baz>()", code);
    }

    // ── v2: Keyed services ──────────────────────────────────────────

    [Fact]
    public void Keyed_generates_inside_ifdef()
    {
        var model = new InjectableEmitModel("App", new[]
        {
            new InjectableServiceModel("global::App.Primary", new[] { "global::App.IDb" }, "Singleton", key: "primary")
        });

        var code = InjectableEmitter.EmitMicrosoft(model);

        Assert.Contains("#if NET8_0_OR_GREATER", code);
        Assert.Contains("#endif", code);
        Assert.Contains("services.AddKeyedSingleton<global::App.IDb, global::App.Primary>(\"primary\")", code);
    }

    [Fact]
    public void Keyed_TryAdd_generates_TryAddKeyed()
    {
        var model = new InjectableEmitModel("App", new[]
        {
            new InjectableServiceModel("global::App.Backup", new[] { "global::App.IDb" }, "Scoped", key: "backup", tryAdd: true)
        });

        var code = InjectableEmitter.EmitMicrosoft(model);

        Assert.Contains("services.TryAddKeyedScoped<global::App.IDb, global::App.Backup>(\"backup\")", code);
    }

    // ── v2: Open generics ───────────────────────────────────────────

    [Fact]
    public void OpenGeneric_generates_typeof_registration()
    {
        var model = new InjectableEmitModel("App", new[]
        {
            new InjectableServiceModel("global::App.Repo<>", new[] { "global::App.IRepo<>" }, "Scoped", isOpenGeneric: true)
        });

        var code = InjectableEmitter.EmitMicrosoft(model);

        Assert.Contains("services.AddScoped(typeof(global::App.IRepo<>), typeof(global::App.Repo<>))", code);
    }

    [Fact]
    public void OpenGeneric_self_registration()
    {
        var model = new InjectableEmitModel("App", new[]
        {
            new InjectableServiceModel("global::App.Handler<>", new string[0], "Transient", isOpenGeneric: true)
        });

        var code = InjectableEmitter.EmitMicrosoft(model);

        Assert.Contains("services.AddTransient(typeof(global::App.Handler<>))", code);
    }

    [Fact]
    public void OpenGeneric_TryAdd()
    {
        var model = new InjectableEmitModel("App", new[]
        {
            new InjectableServiceModel("global::App.Repo<>", new[] { "global::App.IRepo<>" }, "Scoped", tryAdd: true, isOpenGeneric: true)
        });

        var code = InjectableEmitter.EmitMicrosoft(model);

        Assert.Contains("services.TryAddScoped(typeof(global::App.IRepo<>), typeof(global::App.Repo<>))", code);
    }

    // ── v2: Decorators ──────────────────────────────────────────────

    [Fact]
    public void Decorator_generates_service_replacement()
    {
        var model = new InjectableEmitModel("App",
            new[] { new InjectableServiceModel("global::App.RealFoo", new[] { "global::App.IFoo" }, "Singleton") },
            new[] { new InjectableDecoratorModel("global::App.LoggingFoo", "global::App.IFoo") });

        var code = InjectableEmitter.EmitMicrosoft(model);

        Assert.Contains("services.AddSingleton<global::App.IFoo, global::App.RealFoo>()", code);
        Assert.Contains("typeof(global::App.IFoo)", code);
        Assert.Contains("ActivatorUtilities.CreateInstance<global::App.LoggingFoo>", code);
    }

    [Fact]
    public void Multiple_decorators_ordered()
    {
        var model = new InjectableEmitModel("App",
            new[] { new InjectableServiceModel("global::App.RealFoo", new[] { "global::App.IFoo" }, "Singleton") },
            new[]
            {
                new InjectableDecoratorModel("global::App.CachingFoo", "global::App.IFoo", order: 1),
                new InjectableDecoratorModel("global::App.LoggingFoo", "global::App.IFoo", order: 0)
            });

        var code = InjectableEmitter.EmitMicrosoft(model);

        // LoggingFoo (order 0) should appear before CachingFoo (order 1)
        var loggingPos = code.IndexOf("LoggingFoo");
        var cachingPos = code.IndexOf("CachingFoo");
        Assert.True(loggingPos < cachingPos, "LoggingFoo (order 0) should be emitted before CachingFoo (order 1)");
    }

    // ── v2: Mixed standard + keyed ──────────────────────────────────

    [Fact]
    public void Mixed_standard_and_keyed_services()
    {
        var model = new InjectableEmitModel("App", new[]
        {
            new InjectableServiceModel("global::App.DefaultDb", new[] { "global::App.IDb" }, "Singleton"),
            new InjectableServiceModel("global::App.ReadDb", new[] { "global::App.IDb" }, "Singleton", key: "read"),
            new InjectableServiceModel("global::App.WriteDb", new[] { "global::App.IDb" }, "Singleton", key: "write")
        });

        var code = InjectableEmitter.EmitMicrosoft(model);

        // Standard outside #if
        Assert.Contains("services.AddSingleton<global::App.IDb, global::App.DefaultDb>()", code);

        // Keyed inside #if
        Assert.Contains("#if NET8_0_OR_GREATER", code);
        Assert.Contains("AddKeyedSingleton<global::App.IDb, global::App.ReadDb>(\"read\")", code);
        Assert.Contains("AddKeyedSingleton<global::App.IDb, global::App.WriteDb>(\"write\")", code);
    }
}
