using FrenchExDev.Net.Injectable.SourceGenerator.Lib;
using Xunit;

namespace FrenchExDev.Net.Injectable.SourceGenerator.Lib.Tests;

public class EmitDryIocTests
{
    // ── v1 tests (backward compatibility) ───────────────────────────

    [Fact]
    public void Generates_singleton_with_interface()
    {
        var model = new InjectableEmitModel("TestApp", new[]
        {
            new InjectableServiceModel("global::TestApp.Foo", new[] { "global::TestApp.IFoo" }, "Singleton")
        });

        var code = InjectableEmitter.EmitDryIoc(model);

        Assert.Contains("container.Register<global::TestApp.IFoo, global::TestApp.Foo>(global::DryIoc.Reuse.Singleton)", code);
        Assert.Contains("AddTestAppInjectables", code);
        Assert.Contains("namespace DryIoc;", code);
    }

    [Fact]
    public void Generates_scoped_with_interface()
    {
        var model = new InjectableEmitModel("TestApp", new[]
        {
            new InjectableServiceModel("global::TestApp.Bar", new[] { "global::TestApp.IBar" }, "Scoped")
        });

        var code = InjectableEmitter.EmitDryIoc(model);

        Assert.Contains("container.Register<global::TestApp.IBar, global::TestApp.Bar>(global::DryIoc.Reuse.ScopedOrSingleton)", code);
    }

    [Fact]
    public void Generates_transient_self_registration()
    {
        var model = new InjectableEmitModel("TestApp", new[]
        {
            new InjectableServiceModel("global::TestApp.Baz", new string[0], "Transient")
        });

        var code = InjectableEmitter.EmitDryIoc(model);

        Assert.Contains("container.Register<global::TestApp.Baz>(global::DryIoc.Reuse.Transient)", code);
    }

    [Fact]
    public void Generates_multiple_interfaces()
    {
        var model = new InjectableEmitModel("TestApp", new[]
        {
            new InjectableServiceModel("global::TestApp.Multi", new[] { "global::TestApp.IA", "global::TestApp.IB" }, "Singleton")
        });

        var code = InjectableEmitter.EmitDryIoc(model);

        Assert.Contains("container.Register<global::TestApp.IA, global::TestApp.Multi>(global::DryIoc.Reuse.Singleton)", code);
        Assert.Contains("container.Register<global::TestApp.IB, global::TestApp.Multi>(global::DryIoc.Reuse.Singleton)", code);
    }

    [Fact]
    public void Contains_auto_generated_header()
    {
        var model = new InjectableEmitModel("X", new[]
        {
            new InjectableServiceModel("global::X.S", new string[0], "Transient")
        });

        var code = InjectableEmitter.EmitDryIoc(model);

        Assert.StartsWith("// <auto-generated />", code);
        Assert.Contains("#nullable enable", code);
    }

    [Fact]
    public void Returns_IContainer()
    {
        var model = new InjectableEmitModel("X", new[]
        {
            new InjectableServiceModel("global::X.S", new string[0], "Transient")
        });

        var code = InjectableEmitter.EmitDryIoc(model);

        Assert.Contains("return container;", code);
    }

    [Fact]
    public void Unknown_scope_defaults_to_transient()
    {
        var model = new InjectableEmitModel("X", new[]
        {
            new InjectableServiceModel("global::X.S", new[] { "global::X.IS" }, "UnknownScope")
        });

        var code = InjectableEmitter.EmitDryIoc(model);

        Assert.Contains("global::DryIoc.Reuse.Transient", code);
    }

    [Fact]
    public void Multiple_services_all_emitted()
    {
        var model = new InjectableEmitModel("App", new[]
        {
            new InjectableServiceModel("global::App.A", new[] { "global::App.IA" }, "Singleton"),
            new InjectableServiceModel("global::App.B", new string[0], "Transient"),
            new InjectableServiceModel("global::App.C", new[] { "global::App.IC" }, "Scoped")
        });

        var code = InjectableEmitter.EmitDryIoc(model);

        Assert.Contains("Register<global::App.IA, global::App.A>(global::DryIoc.Reuse.Singleton)", code);
        Assert.Contains("Register<global::App.B>(global::DryIoc.Reuse.Transient)", code);
        Assert.Contains("Register<global::App.IC, global::App.C>(global::DryIoc.Reuse.ScopedOrSingleton)", code);
    }

    // ── v2: TryAdd ──────────────────────────────────────────────────

    [Fact]
    public void TryAdd_generates_IfAlreadyRegistered_Keep()
    {
        var model = new InjectableEmitModel("App", new[]
        {
            new InjectableServiceModel("global::App.Foo", new[] { "global::App.IFoo" }, "Singleton", tryAdd: true)
        });

        var code = InjectableEmitter.EmitDryIoc(model);

        Assert.Contains("ifAlreadyRegistered: global::DryIoc.IfAlreadyRegistered.Keep", code);
    }

    [Fact]
    public void TryAdd_self_registration()
    {
        var model = new InjectableEmitModel("App", new[]
        {
            new InjectableServiceModel("global::App.Baz", new string[0], "Transient", tryAdd: true)
        });

        var code = InjectableEmitter.EmitDryIoc(model);

        Assert.Contains("container.Register<global::App.Baz>(global::DryIoc.Reuse.Transient, ifAlreadyRegistered: global::DryIoc.IfAlreadyRegistered.Keep)", code);
    }

    // ── v2: Keyed services ──────────────────────────────────────────

    [Fact]
    public void Keyed_generates_serviceKey()
    {
        var model = new InjectableEmitModel("App", new[]
        {
            new InjectableServiceModel("global::App.Primary", new[] { "global::App.IDb" }, "Singleton", key: "primary")
        });

        var code = InjectableEmitter.EmitDryIoc(model);

        Assert.Contains("serviceKey: \"primary\"", code);
        Assert.Contains("global::DryIoc.Reuse.Singleton", code);
    }

    [Fact]
    public void Keyed_TryAdd()
    {
        var model = new InjectableEmitModel("App", new[]
        {
            new InjectableServiceModel("global::App.Backup", new[] { "global::App.IDb" }, "Scoped", key: "backup", tryAdd: true)
        });

        var code = InjectableEmitter.EmitDryIoc(model);

        Assert.Contains("serviceKey: \"backup\"", code);
        Assert.Contains("ifAlreadyRegistered: global::DryIoc.IfAlreadyRegistered.Keep", code);
    }

    // ── v2: Open generics ───────────────────────────────────────────

    [Fact]
    public void OpenGeneric_generates_typeof_registration()
    {
        var model = new InjectableEmitModel("App", new[]
        {
            new InjectableServiceModel("global::App.Repo<>", new[] { "global::App.IRepo<>" }, "Scoped", isOpenGeneric: true)
        });

        var code = InjectableEmitter.EmitDryIoc(model);

        Assert.Contains("container.Register(typeof(global::App.IRepo<>), typeof(global::App.Repo<>), reuse: global::DryIoc.Reuse.ScopedOrSingleton)", code);
    }

    [Fact]
    public void OpenGeneric_self_registration()
    {
        var model = new InjectableEmitModel("App", new[]
        {
            new InjectableServiceModel("global::App.Handler<>", new string[0], "Transient", isOpenGeneric: true)
        });

        var code = InjectableEmitter.EmitDryIoc(model);

        Assert.Contains("container.Register(typeof(global::App.Handler<>), reuse: global::DryIoc.Reuse.Transient)", code);
    }

    // ── v2: Decorators ──────────────────────────────────────────────

    [Fact]
    public void Decorator_generates_Setup_Decorator()
    {
        var model = new InjectableEmitModel("App",
            new[] { new InjectableServiceModel("global::App.RealFoo", new[] { "global::App.IFoo" }, "Singleton") },
            new[] { new InjectableDecoratorModel("global::App.LoggingFoo", "global::App.IFoo") });

        var code = InjectableEmitter.EmitDryIoc(model);

        Assert.Contains("container.Register<global::App.IFoo, global::App.LoggingFoo>(setup: global::DryIoc.Setup.Decorator)", code);
    }

    [Fact]
    public void Multiple_decorators_ordered()
    {
        var model = new InjectableEmitModel("App",
            new[] { new InjectableServiceModel("global::App.RealFoo", new[] { "global::App.IFoo" }, "Singleton") },
            new[]
            {
                new InjectableDecoratorModel("global::App.CachingFoo", "global::App.IFoo", order: 1),
                new InjectableDecoratorModel("global::App.LoggingFoo", "global::App.IFoo", order: 0)
            });

        var code = InjectableEmitter.EmitDryIoc(model);

        var loggingPos = code.IndexOf("LoggingFoo");
        var cachingPos = code.IndexOf("CachingFoo");
        Assert.True(loggingPos < cachingPos, "LoggingFoo (order 0) should be emitted before CachingFoo (order 1)");
    }
}
