namespace FrenchExDev.Net.Ddd.Entity.Dsl.SourceGenerator.Lib;

using System.Collections.Generic;
using System.Text;

/// <summary>
/// Emits Entity.Dsl attributes on partial classes based on DDD attribute analysis.
/// Maps DDD concepts → Entity.Dsl concepts.
/// </summary>
public static class DddEntityDslBridgeEmitter
{
    /// <summary>
    /// Emits a partial class with [MappedEntity] and mapped Entity.Dsl attributes.
    /// </summary>
    public static string Emit(DddBridgeModel model)
    {
        var sb = new StringBuilder(1024);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Ddd.Entity.Dsl bridge — maps DDD attributes to Entity.Dsl attributes.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();

        // Class-level attributes
        sb.AppendLine("[global::FrenchExDev.Net.Entity.Dsl.Attributes.MappedEntity]");

        sb.AppendLine($"public partial class {model.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine("}");
        return sb.ToString();
    }
}

/// <summary>
/// Represents a DDD-decorated class that needs Entity.Dsl bridge attributes.
/// </summary>
public sealed class DddBridgeModel
{
    public string Namespace { get; set; } = "";
    public string ClassName { get; set; } = "";
    public bool IsAggregateRoot { get; set; }
    public bool IsEntity { get; set; }

    /// <summary>Properties with [EntityId] that need [PrimaryKey] mapping.</summary>
    public List<string> EntityIdPropertyNames { get; set; } = new List<string>();

    /// <summary>Properties with [Composition] that need OnDelete="Cascade".</summary>
    public List<string> CompositionPropertyNames { get; set; } = new List<string>();

    /// <summary>Properties with [Aggregation] that need OnDelete="Restrict".</summary>
    public List<string> AggregationPropertyNames { get; set; } = new List<string>();

    /// <summary>Properties with [Association] that need OnDelete="NoAction".</summary>
    public List<string> AssociationPropertyNames { get; set; } = new List<string>();
}
