using System.Collections.Generic;
using System.Text;

namespace FrenchExDev.Net.GitLab.Ci.Yaml.SourceGenerator;

internal static class ModelClassEmitter
{
    private static readonly HashSet<string> HelperDefinitions = new()
    {
        "string_or_list", "stringOrList",
        "string_file_list", "include_item", "!reference",
        "image", "services", "identity",
        "script", "steps", "optional_script",
        "before_script", "after_script",
        "rules", "includeRules",
        "workflowName", "if", "changes", "exists",
        "timeout", "start_in", "rulesNeeds",
        "allow_failure", "parallel", "parallel_matrix",
        "when", "cache", "filter_refs", "filter",
        "retry", "retry_max", "retry_errors",
        "interruptible",
        "tags", "step", "stepName", "stepFuncReference",
        "configInputs", "jobInputs", "inputs",
        "globalVariables", "jobVariables", "rulesVariables",
        "id_tokens", "secrets",
        "stepNamedStrings", "stepNamedValues",
    };

    public static string EmitGitLabCiFile(string ns, UnifiedSchema schema)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        sb.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine("public partial class GitLabCiFile");
        sb.AppendLine("{");

        foreach (var up in schema.RootProperties)
        {
            var prop = up.Property;
            var type = MapRootPropertyType(prop);
            EmitVersionAttributes(sb, up);
            if (prop.IsDeprecated)
                sb.AppendLine("    [global::System.Obsolete(\"Deprecated.\")]");
            if (prop.Description is not null)
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {EscapeXml(prop.Description)}");
                sb.AppendLine("    /// </summary>");
            }
            sb.AppendLine($"    public {type} {prop.CSharpName} {{ get; set; }}");
            sb.AppendLine();
        }

        // Jobs dictionary — arbitrary job names at root level
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Named jobs. In YAML these appear as top-level keys (not under a 'jobs' key).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public global::System.Collections.Generic.Dictionary<string, GitLabCiJob>? Jobs { get; set; }");
        sb.AppendLine();

        sb.AppendLine("    public global::System.Collections.Generic.Dictionary<string, object?>? Extensions { get; set; }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static IEnumerable<(string FileName, string Source)> EmitDefinitions(string ns, UnifiedSchema schema)
    {
        foreach (var kvp in schema.Definitions)
        {
            var defName = kvp.Key;
            var def = kvp.Value;

            if (HelperDefinitions.Contains(defName))
                continue;
            if (def.Properties.Count == 0)
                continue;

            var className = NamingHelper.DefinitionToClassName(defName);
            var source = EmitClass(ns, className, def.Description, def.Properties,
                def.SinceVersion, def.UntilVersion);
            yield return ($"{className}.g.cs", source);

            // Emit inline object classes found in properties
            foreach (var inline in CollectInlineClasses(ns, def.Properties))
                yield return inline;
        }

        // Also collect inline classes from root properties
        foreach (var inline in CollectInlineClasses(ns, schema.RootProperties))
            yield return inline;
    }

    private static IEnumerable<(string FileName, string Source)> CollectInlineClasses(
        string ns, List<UnifiedProperty> properties)
    {
        foreach (var up in properties)
        {
            var prop = up.Property;

            // Inline object property
            if (prop.Type == PropertyType.InlineObject &&
                prop.InlineClassName is not null &&
                prop.InlineObjectProperties is not null)
            {
                var unifiedProps = prop.InlineObjectProperties
                    .ConvertAll(p => new UnifiedProperty { Property = p });
                var source = EmitClass(ns, prop.InlineClassName, null, unifiedProps, null, null);
                yield return ($"{prop.InlineClassName}.g.cs", source);

                // Recurse into nested inline objects
                foreach (var nested in CollectInlineClasses(ns, unifiedProps))
                    yield return nested;
            }

            // oneOf[string, object] with inline object
            if (prop.Type == PropertyType.StringOrObject &&
                prop.OneOfObjectClassName is not null &&
                prop.OneOfObjectProperties is not null)
            {
                var unifiedProps = prop.OneOfObjectProperties
                    .ConvertAll(p => new UnifiedProperty { Property = p });
                var source = EmitClass(ns, prop.OneOfObjectClassName, null, unifiedProps, null, null);
                yield return ($"{prop.OneOfObjectClassName}.g.cs", source);

                foreach (var nested in CollectInlineClasses(ns, unifiedProps))
                    yield return nested;
            }

            // Array of inline objects
            if (prop.Type == PropertyType.Array &&
                prop.Items?.Type == PropertyType.InlineObject &&
                prop.Items.InlineClassName is not null &&
                prop.Items.InlineObjectProperties is not null)
            {
                var unifiedProps = prop.Items.InlineObjectProperties
                    .ConvertAll(p => new UnifiedProperty { Property = p });
                var source = EmitClass(ns, prop.Items.InlineClassName, null, unifiedProps, null, null);
                yield return ($"{prop.Items.InlineClassName}.g.cs", source);

                foreach (var nested in CollectInlineClasses(ns, unifiedProps))
                    yield return nested;
            }

            // Array of oneOf items with inline object
            if (prop.Type == PropertyType.Array &&
                prop.Items?.Type == PropertyType.StringOrObject &&
                prop.Items.OneOfObjectClassName is not null &&
                prop.Items.OneOfObjectProperties is not null)
            {
                var unifiedProps = prop.Items.OneOfObjectProperties
                    .ConvertAll(p => new UnifiedProperty { Property = p });
                var source = EmitClass(ns, prop.Items.OneOfObjectClassName, null, unifiedProps, null, null);
                yield return ($"{prop.Items.OneOfObjectClassName}.g.cs", source);

                foreach (var nested in CollectInlineClasses(ns, unifiedProps))
                    yield return nested;
            }
        }
    }

    private static string EmitClass(string ns, string className, string? description,
        List<UnifiedProperty> properties, string? sinceVersion, string? untilVersion)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        if (description is not null)
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// {EscapeXml(description)}");
            sb.AppendLine("/// </summary>");
        }

        EmitVersionAttributes(sb, sinceVersion, untilVersion, "");

        sb.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine($"public partial class {className}");
        sb.AppendLine("{");

        foreach (var up in properties)
        {
            var prop = up.Property;
            var type = NamingHelper.MapCSharpType(prop);

            if (prop.Description is not null)
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {EscapeXml(prop.Description)}");
                sb.AppendLine("    /// </summary>");
            }
            EmitVersionAttributes(sb, up);
            if (prop.IsDeprecated)
                sb.AppendLine("    [global::System.Obsolete(\"Deprecated.\")]");
            sb.AppendLine($"    public {type} {prop.CSharpName} {{ get; set; }}");
            sb.AppendLine();
        }

        sb.AppendLine("    public global::System.Collections.Generic.Dictionary<string, object?>? Extensions { get; set; }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string MapRootPropertyType(PropertyModel prop)
    {
        // Most root properties use their natural types from the schema
        return NamingHelper.MapCSharpType(prop);
    }

    private static void EmitVersionAttributes(StringBuilder sb, UnifiedProperty up)
    {
        EmitVersionAttributes(sb, up.SinceVersion, up.UntilVersion, "    ");
    }

    private static void EmitVersionAttributes(StringBuilder sb, string? since, string? until, string indent)
    {
        if (since is not null)
            sb.AppendLine($"{indent}[SinceVersion(\"{since}\")]");
        if (until is not null)
            sb.AppendLine($"{indent}[UntilVersion(\"{until}\")]");
    }

    private static string EscapeXml(string text)
    {
        return text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
    }
}
