using System.Text;

namespace FrenchExDev.Net.GitLab.Ci.Yaml.SourceGenerator;

internal static class VersionMetadataEmitter
{
    public static string Emit(string ns, UnifiedSchema schema)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine("public static class GitLabCiSchemaVersions");
        sb.AppendLine("{");

        // Version list
        sb.AppendLine("    private static readonly global::System.Collections.Generic.List<string> _versions = new()");
        sb.AppendLine("    {");
        foreach (var v in schema.Versions)
            sb.AppendLine($"        \"{v}\",");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public static global::System.Collections.Generic.IReadOnlyList<string> Available => _versions;");
        sb.AppendLine();

        if (schema.Versions.Count > 0)
        {
            sb.AppendLine($"    public static string Latest => \"{schema.Versions[schema.Versions.Count - 1]}\";");
            sb.AppendLine($"    public static string Oldest => \"{schema.Versions[0]}\";");
        }

        sb.AppendLine("}");
        sb.AppendLine();
        // Version attributes
        sb.AppendLine("[global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Method | global::System.AttributeTargets.Class, AllowMultiple = false)]");
        sb.AppendLine("public sealed class SinceVersionAttribute : global::System.Attribute");
        sb.AppendLine("{");
        sb.AppendLine("    public string Version { get; }");
        sb.AppendLine("    public SinceVersionAttribute(string version) => Version = version;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("[global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Method | global::System.AttributeTargets.Class, AllowMultiple = false)]");
        sb.AppendLine("public sealed class UntilVersionAttribute : global::System.Attribute");
        sb.AppendLine("{");
        sb.AppendLine("    public string Version { get; }");
        sb.AppendLine("    public UntilVersionAttribute(string version) => Version = version;");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
