using System.Collections.Generic;
using System.Text;

namespace FrenchExDev.Net.GitLab.DockerCompose.SourceGenerator;

/// <summary>
/// Emits C# model classes from the unified GitLab configuration model.
/// </summary>
internal static class GitLabConfigEmitter
{
    public static string EmitModelClass(
        string ns, string className, UnifiedObjectNode node,
        List<PropertyInfo> properties, string? sinceVersion, string? untilVersion)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        if (sinceVersion != null)
            sb.AppendLine($"[SinceVersion(\"{sinceVersion}\")]");
        if (untilVersion != null)
            sb.AppendLine($"[UntilVersion(\"{untilVersion}\")]");

        sb.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine($"public partial class {className}");
        sb.AppendLine("{");

        foreach (var prop in properties)
        {
            if (prop.DocComment != null)
            {
                var escaped = EscapeXml(prop.DocComment);
                sb.AppendLine($"    /// <summary>{escaped}</summary>");
            }

            if (prop.SinceVersion != null)
                sb.AppendLine($"    [SinceVersion(\"{prop.SinceVersion}\")]");
            if (prop.UntilVersion != null)
                sb.AppendLine($"    [UntilVersion(\"{prop.UntilVersion}\")]");

            sb.AppendLine($"    public {prop.CSharpType} {prop.Name} {{ get; set; }}");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string EmitVersionMetadata(string ns, UnifiedGitLabRbModel unified)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        // SinceVersion attribute
        sb.AppendLine("[global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Class | global::System.AttributeTargets.Method, AllowMultiple = false)]");
        sb.AppendLine("internal sealed class SinceVersionAttribute : global::System.Attribute");
        sb.AppendLine("{");
        sb.AppendLine("    public string Version { get; }");
        sb.AppendLine("    public SinceVersionAttribute(string version) => Version = version;");
        sb.AppendLine("}");
        sb.AppendLine();

        // UntilVersion attribute
        sb.AppendLine("[global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Class | global::System.AttributeTargets.Method, AllowMultiple = false)]");
        sb.AppendLine("internal sealed class UntilVersionAttribute : global::System.Attribute");
        sb.AppendLine("{");
        sb.AppendLine("    public string Version { get; }");
        sb.AppendLine("    public UntilVersionAttribute(string version) => Version = version;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Version list
        sb.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine("public static class GitLabOmnibusVersions");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly string[] _versions = new[]");
        sb.AppendLine("    {");
        foreach (var v in unified.Versions)
            sb.AppendLine($"        \"{v}\",");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public static global::System.Collections.Generic.IReadOnlyList<string> Available => _versions;");
        sb.AppendLine($"    public static string Latest => \"{unified.Versions[unified.Versions.Count - 1]}\";");
        sb.AppendLine($"    public static string Oldest => \"{unified.Versions[0]}\";");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitRbMetadata(
        string ns, List<MetadataEntry> entries, List<string> standaloneUrls)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        // Value kind enum
        sb.AppendLine("public enum GitLabRbValueKind");
        sb.AppendLine("{");
        sb.AppendLine("    String, Integer, Long, Boolean, Float, StringList, FloatList, StringDict, SubObject, ArrayOfObjects, Nil,");
        sb.AppendLine("}");
        sb.AppendLine();

        // Property metadata record
        sb.AppendLine("public sealed record GitLabRbPropertyMeta(string Prefix, string[] KeyPath, GitLabRbValueKind ValueKind);");
        sb.AppendLine();

        // Metadata class
        sb.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine("public static class GitLabRbMetadata");
        sb.AppendLine("{");

        sb.AppendLine("    public static readonly global::System.Collections.Generic.IReadOnlyList<GitLabRbPropertyMeta> Properties = new GitLabRbPropertyMeta[]");
        sb.AppendLine("    {");
        foreach (var entry in entries)
        {
            var keyPathStr = string.Join(", ", entry.KeyPath.ConvertAll(k => $"\"{EscapeString(k)}\""));
            sb.AppendLine($"        new(\"{EscapeString(entry.Prefix)}\", new[] {{ {keyPathStr} }}, GitLabRbValueKind.{entry.ValueKind}),");
        }
        sb.AppendLine("    };");
        sb.AppendLine();

        sb.AppendLine("    public static readonly global::System.Collections.Generic.IReadOnlyList<string> StandaloneUrls = new[]");
        sb.AppendLine("    {");
        foreach (var url in standaloneUrls)
            sb.AppendLine($"        \"{EscapeString(url)}\",");
        sb.AppendLine("    };");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EscapeString(string text) =>
        text.Replace("\\", "\\\\").Replace("\"", "\\\"")
            .Replace("\r", "\\r").Replace("\n", "\\n").Replace("\t", "\\t")
            .Replace("\0", "\\0").Replace("\u2028", "\\u2028").Replace("\u2029", "\\u2029");

    private static string EscapeXml(string text)
    {
        return text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;")
            .Replace("\r", "&#13;").Replace("\n", "&#10;").Replace("\u2028", "&#8232;").Replace("\u2029", "&#8233;");
    }

    /// <summary>Property info for emission.</summary>
    internal sealed class PropertyInfo
    {
        public string Name { get; set; } = "";
        public string CSharpType { get; set; } = "";
        public string? DocComment { get; set; }
        public string? SinceVersion { get; set; }
        public string? UntilVersion { get; set; }
    }

    /// <summary>Metadata entry for rendering.</summary>
    internal sealed class MetadataEntry
    {
        public string Prefix { get; set; } = "";
        public List<string> KeyPath { get; set; } = new List<string>();
        public string ValueKind { get; set; } = "String";
    }
}
