<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>quality-gate</ToolCommandName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../FrenchExDev.Net.QualityGate/FrenchExDev.Net.QualityGate.csproj" />
    <ProjectReference Include="../FrenchExDev.Net.QualityGate.Html/FrenchExDev.Net.QualityGate.Html.csproj" />
  </ItemGroup>

</Project>
