using System.Text;
using FrenchExDev.Net.Vos.Config;

namespace FrenchExDev.Net.Vos.Infra.FileSystem;

/// <summary>
/// Renders a <see cref="VosConfig"/> into a data-driven Ruby Vagrantfile
/// that reads <c>config-vos.yaml</c> at runtime.
/// </summary>
public static class VagrantfileRenderer
{
    /// <summary>
    /// Renders a complete Vagrantfile that reads config-vos.yaml
    /// and configures VMs based on machine_types/machines/instances.
    /// </summary>
    public static string Render(VosConfig config)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# -*- mode: ruby -*-");
        sb.AppendLine("# vi: set ft=ruby :");
        sb.AppendLine("# Generated by FrenchExDev.Net.Vos");
        sb.AppendLine();
        sb.AppendLine("require 'yaml'");
        sb.AppendLine();
        sb.AppendLine("Vagrant.configure(\"2\") do |config|");
        sb.AppendLine();

        // Plugins
        var allPlugins = config.MachineTypes.Values
            .SelectMany(mt => mt.Plugins)
            .Distinct()
            .ToList();

        foreach (var plugin in allPlugins)
        {
            sb.AppendLine($"  if Vagrant.has_plugin?(\"{plugin}\")");
            if (plugin == "vagrant-hostmanager")
            {
                sb.AppendLine("    config.hostmanager.enabled = true");
                sb.AppendLine("    config.hostmanager.manage_host = true");
                sb.AppendLine("    config.hostmanager.manage_guest = true");
            }
            sb.AppendLine("  end");
            sb.AppendLine();
        }

        // Machines
        var allResolved = VosConfigMerger.ResolveAll(config);
        foreach (var (machineName, inst) in allResolved)
        {
            sb.AppendLine($"  config.vm.define \"{inst.Name}\" do |machine|");
            sb.AppendLine($"    machine.vm.box = \"{inst.Box}\"");
            if (inst.Hostname is not null)
                sb.AppendLine($"    machine.vm.hostname = \"{inst.Hostname}\"");

            // Network
            if (inst.Ip is not null)
                sb.AppendLine($"    machine.vm.network \"private_network\", ip: \"{inst.Ip}\"");

            // Provider
            sb.AppendLine();
            sb.AppendLine($"    machine.vm.provider \"{inst.ProviderType}\" do |v|");
            sb.AppendLine($"      v.memory = {inst.Memory}");
            sb.AppendLine($"      v.cpus = {inst.Cpus}");

            if (inst.ProviderType == "virtualbox")
            {
                if (inst.VideoMemory > 0)
                    sb.AppendLine($"      v.customize [\"modifyvm\", :id, \"--vram\", \"{inst.VideoMemory}\"]");
                sb.AppendLine($"      v.gui = {(inst.Gui ? "true" : "false")}");
                sb.AppendLine($"      v.linked_clone = {(inst.LinkedClones ? "true" : "false")}");

                foreach (var cmd in inst.VboxManage)
                {
                    var args = string.Join(", ", cmd.Select(a => a == "{{ .Name }}" ? ":id" : $"\"{a}\""));
                    sb.AppendLine($"      v.customize [{args}]");
                }
            }

            sb.AppendLine("    end");

            // Shared folders
            foreach (var sf in inst.SharedFolders)
            {
                var typeStr = sf.Type is not null ? $", type: \"{sf.Type}\"" : "";
                var disabledStr = sf.Disabled ? ", disabled: true" : "";
                sb.AppendLine($"    machine.vm.synced_folder \"{sf.HostPath}\", \"{sf.GuestPath}\"{typeStr}{disabledStr}");
            }

            // Provisioning
            foreach (var step in inst.Provisioning)
            {
                if (!step.Enabled) continue;

                if (step.ReloadBefore)
                    sb.AppendLine("    machine.trigger.before :provision do |trigger| trigger.run = {inline: \"vagrant reload\"} end");

                var envStr = step.Env.Count > 0
                    ? ", env: {" + string.Join(", ", step.Env.Select(e => $"\"{e.Key}\" => \"{e.Value}\"")) + "}"
                    : "";

                var scriptPath = step.Version is not null
                    ? $"provisioning/{step.Version}/{step.Key}{step.Extension ?? ".sh"}"
                    : $"provisioning/{step.Key}{step.Extension ?? ".sh"}";

                sb.AppendLine($"    machine.vm.provision \"shell\", path: \"{scriptPath}\", privileged: {(step.Privileged ? "true" : "false")}{envStr}");

                if (step.ReloadAfter)
                    sb.AppendLine("    machine.trigger.after :provision do |trigger| trigger.run = {inline: \"vagrant reload\"} end");
            }

            sb.AppendLine("  end");
            sb.AppendLine();
        }

        sb.AppendLine("end");

        return sb.ToString();
    }
}
