<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net11.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="SimpleInjector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FrenchExDev.Net.Injectable.Attributes\FrenchExDev.Net.Injectable.Attributes.csproj" />
    <ProjectReference Include="..\..\src\FrenchExDev.Net.Injectable.SimpleInjector.SourceGenerator\FrenchExDev.Net.Injectable.SimpleInjector.SourceGenerator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
