namespace FrenchExDev.Net.Packer.Bundle.Hcl2;

/// <summary>
/// Models a <c>source "type" "name" { ... }</c> block.
/// Wraps a dictionary of HCL arguments (key → value).
/// The plugin-specific strongly-typed records are generated by the SG;
/// this base class supports any source via raw arguments.
/// </summary>
public sealed record PackerSource
{
    public required string Type { get; init; }
    public required string Name { get; init; }

    /// <summary>
    /// HCL arguments for this source block. Keys are HCL field names (snake_case),
    /// values are typed (string, int, bool, list, map, list-of-lists, or raw HCL expression).
    /// </summary>
    public Dictionary<string, object?> Arguments { get; init; } = new();

    /// <summary>Writes this source as HCL2 to the given writer.</summary>
    public void WriteTo(HclWriter writer)
    {
        using var block = writer.Block("source", Type, Name);

        foreach (var kvp in Arguments)
        {
            if (kvp.Value is null) continue;
            WriteArgument(writer, kvp.Key, kvp.Value);
        }
    }

    internal static void WriteArgument(HclWriter writer, string name, object value)
    {
        switch (value)
        {
            case string s:
                writer.Argument(name, s);
                break;
            case int i:
                writer.Argument(name, i);
                break;
            case uint u:
                writer.Argument(name, u);
                break;
            case bool b:
                writer.Argument(name, b);
                break;
            case IReadOnlyList<IReadOnlyList<string>> lol:
                writer.ArgumentListOfLists(name, lol);
                break;
            case IReadOnlyList<string> list:
                writer.ArgumentList(name, list);
                break;
            case IReadOnlyDictionary<string, string> map:
                writer.ArgumentMap(name, map);
                break;
            case HclExpression expr:
                writer.Expression(name, expr.Value);
                break;
            default:
                writer.Argument(name, value.ToString());
                break;
        }
    }
}

/// <summary>
/// Wrapper for raw HCL expressions (e.g. <c>var.name</c>, <c>local.timestamp</c>)
/// that should be emitted without quotes.
/// </summary>
public sealed record HclExpression(string Value)
{
    public override string ToString() => Value;
}

/// <summary>Static helpers for building HCL2 expressions.</summary>
public static class Hcl
{
    public static HclExpression Var(string name) => new($"var.{name}");
    public static HclExpression Local(string name) => new($"local.{name}");
    public static HclExpression Data(string type, string name, string attribute) => new($"data.{type}.{name}.{attribute}");
    public static HclExpression Func(string function, params string[] args) => new($"{function}({string.Join(", ", args)})");
    public static HclExpression Raw(string expression) => new(expression);
}
