namespace FrenchExDev.Net.Packer.Bundle.Hcl2;

/// <summary>
/// Models a <c>build { }</c> block with sources, provisioners, and post-processors.
/// Immutable record — build via <see cref="PackerBuildBuilder"/>.
/// </summary>
public sealed record PackerBuild
{
    public string? Name { get; init; }
    public IReadOnlyList<string> Sources { get; init; } = [];
    public IReadOnlyList<PackerProvisioner> Provisioners { get; init; } = [];
    public IReadOnlyList<PackerPostProcessor> PostProcessors { get; init; } = [];
    public IReadOnlyList<PackerBuildSourceOverride> SourceOverrides { get; init; } = [];

    /// <summary>Writes this build block as HCL2 to the given writer.</summary>
    public void WriteTo(HclWriter writer)
    {
        using var block = writer.Block("build");

        writer.Argument("name", Name);

        if (Sources.Count > 0)
        {
            writer.BlankLine();
            writer.ArgumentList("sources", Sources as IReadOnlyList<string>);
        }

        foreach (var over in SourceOverrides)
        {
            writer.BlankLine();
            over.WriteTo(writer);
        }

        foreach (var prov in Provisioners)
        {
            writer.BlankLine();
            prov.WriteTo(writer);
        }

        foreach (var pp in PostProcessors)
        {
            writer.BlankLine();
            pp.WriteTo(writer);
        }
    }
}

/// <summary>
/// Per-source overrides inside a build block: <c>source "type.name" { ... }</c>.
/// </summary>
public sealed record PackerBuildSourceOverride
{
    public required string SourceRef { get; init; }
    public Dictionary<string, object?> Arguments { get; init; } = new();

    public void WriteTo(HclWriter writer)
    {
        using var block = writer.Block("source", SourceRef);
        foreach (var kvp in Arguments)
        {
            if (kvp.Value is null) continue;
            PackerSource.WriteArgument(writer, kvp.Key, kvp.Value);
        }
    }
}

/// <summary>
/// Base for provisioner blocks inside a build: <c>provisioner "type" { ... }</c>.
/// Plugin-specific records are generated by the SG.
/// </summary>
public record PackerProvisioner
{
    public required string Type { get; init; }
    public Dictionary<string, object?> Arguments { get; init; } = new();

    /// <summary>Only/except filtering.</summary>
    public IReadOnlyList<string>? Only { get; init; }
    public IReadOnlyList<string>? Except { get; init; }

    public virtual void WriteTo(HclWriter writer)
    {
        using var block = writer.Block("provisioner", Type);

        foreach (var kvp in Arguments)
        {
            if (kvp.Value is null) continue;
            PackerSource.WriteArgument(writer, kvp.Key, kvp.Value);
        }

        if (Only is { Count: > 0 })
            writer.ArgumentList("only", Only);
        if (Except is { Count: > 0 })
            writer.ArgumentList("except", Except);
    }
}

/// <summary>
/// Base for post-processor blocks inside a build: <c>post-processor "type" { ... }</c>.
/// Plugin-specific records are generated by the SG.
/// </summary>
public record PackerPostProcessor
{
    public required string Type { get; init; }
    public Dictionary<string, object?> Arguments { get; init; } = new();

    public IReadOnlyList<string>? Only { get; init; }
    public IReadOnlyList<string>? Except { get; init; }

    public virtual void WriteTo(HclWriter writer)
    {
        using var block = writer.Block("post-processor", Type);

        foreach (var kvp in Arguments)
        {
            if (kvp.Value is null) continue;
            PackerSource.WriteArgument(writer, kvp.Key, kvp.Value);
        }

        if (Only is { Count: > 0 })
            writer.ArgumentList("only", Only);
        if (Except is { Count: > 0 })
            writer.ArgumentList("except", Except);
    }
}

/// <summary>
/// Mutable builder for <see cref="PackerBuild"/>. Lives on the <see cref="PackerBundle"/> workspace.
/// </summary>
public sealed class PackerBuildBuilder
{
    public string? Name { get; set; }
    public List<string> Sources { get; } = new();
    public List<PackerProvisioner> Provisioners { get; } = new();
    public List<PackerPostProcessor> PostProcessors { get; } = new();
    public List<PackerBuildSourceOverride> SourceOverrides { get; } = new();

    public PackerBuildBuilder WithName(string name) { Name = name; return this; }
    public PackerBuildBuilder WithSource(string sourceRef) { Sources.Add(sourceRef); return this; }
    public PackerBuildBuilder WithProvisioner(PackerProvisioner provisioner) { Provisioners.Add(provisioner); return this; }
    public PackerBuildBuilder WithPostProcessor(PackerPostProcessor postProcessor) { PostProcessors.Add(postProcessor); return this; }
    public PackerBuildBuilder WithSourceOverride(PackerBuildSourceOverride over) { SourceOverrides.Add(over); return this; }

    public PackerBuild Build() => new()
    {
        Name = Name,
        Sources = Sources.ToList(),
        Provisioners = Provisioners.ToList(),
        PostProcessors = PostProcessors.ToList(),
        SourceOverrides = SourceOverrides.ToList()
    };
}
